fixed amazonlinux latest version

diff --git a/nginx/1.23.4/almalinux/8.7-20230222/Dockerfile-compat b/nginx/1.23.4/almalinux/8.7-20230222/Dockerfile-compat
--- a/nginx/1.23.4/almalinux/8.7-20230222/Dockerfile-compat
+++ b/nginx/1.23.4/almalinux/8.7-20230222/Dockerfile-compat
@@ -8,8 +8,8 @@
 # Repo: https://github.com/fabiocicerchia/nginx-lua
 
 ARG ARCH=
-ARG DISTRO=alpine
-ARG DISTRO_VER=3.17.3
+ARG DISTRO=almalinux
+ARG DISTRO_VER=8.7-20230222
 
 #############################
 # Settings Common Variables #
@@ -30,7 +30,7 @@ ENV VCS_REF=$VCS_REF
 
 # lua
 # https://www.lua.org/versions.html
-ARG VER_LUA=5.4.4
+ARG VER_LUA=5.3.4
 ENV VER_LUA=$VER_LUA
 
 # ngx_devel_kit
@@ -192,6 +192,9 @@ ENV NGX_CFLAGS=$NGX_CFLAGS
 ARG NGX_LDOPT="-Wl,-rpath,/usr/local/lib -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -pie"
 ENV NGX_LDOPT=$NGX_LDOPT
 # Reference: http://nginx.org/en/docs/configure.html
+# NOTE: Almalinux is building with PCRE instead of PCRE2 mostly due to
+# https://github.com/openresty/lua-nginx-module/issues/1984.
+# More details on it: https://github.com/fabiocicerchia/nginx-lua/pull/40
 ARG NGINX_BUILD_CONFIG="\
             --prefix=/etc/nginx \
             --sbin-path=/usr/sbin/nginx \
@@ -233,6 +236,7 @@ ARG NGINX_BUILD_CONFIG="\
             --with-stream_realip_module \
             --with-stream_ssl_module \
             --with-stream_ssl_preread_module \
+            --without-pcre2 \
             --add-module=/njs-${VER_NJS}/nginx \
             --add-module=/lua-nginx-module-${VER_LUA_NGINX_MODULE} \
             --add-module=/ngx_devel_kit-${VER_NGX_DEVEL_KIT} \
@@ -244,44 +248,35 @@ ARG NGINX_BUILD_CONFIG="\
 ENV NGINX_BUILD_CONFIG=$NGINX_BUILD_CONFIG
 
 ARG BUILD_DEPS_BASE="\
-        curl \
-        geoip-dev \
+        GeoIP-devel \
+        ca-certificates \
+        findutils \
+        gcc-c++ \
         gzip \
+        libxml2-devel \
+        libxslt-devel \
         make \
-        openssl-dev \
+        readline-devel \
+        openssl-devel \
         patch \
-        pcre-dev \
+        pcre-devel \
         tar \
-        zlib-dev \
+        unzip \
+        which \
+        zlib-devel \
 "
 ENV BUILD_DEPS_BASE=$BUILD_DEPS_BASE
 ARG BUILD_DEPS_AMD64="\
         ${BUILD_DEPS_BASE} \
-        g++ \
 "
 ENV BUILD_DEPS_AMD64=$BUILD_DEPS_AMD64
 ARG BUILD_DEPS_ARM64V8="\
         ${BUILD_DEPS_BASE} \
-        gcc-aarch64-none-elf \
 "
 ENV BUILD_DEPS_ARM64V8=$BUILD_DEPS_ARM64V8
 ENV BUILD_DEPS=
 
-ARG NGINX_BUILD_DEPS="\
-# NGINX
-        alpine-sdk \
-        bash \
-        findutils \
-        gcc \
-        libc-dev \
-        libxml2-dev \
-        libxslt-dev \
-        linux-headers \
-        make \
-        openssl-dev \
-        pcre-dev \
-        zlib-dev \
-"
+ARG NGINX_BUILD_DEPS=""
 ENV NGINX_BUILD_DEPS=$NGINX_BUILD_DEPS
 
 ####################################
@@ -292,8 +287,12 @@ FROM base AS builder
 # hadolint ignore=SC2086
 RUN set -eux \
     && eval BUILD_DEPS="\$$(echo BUILD_DEPS_${ARCH} | tr '[:lower:]' '[:upper:]')" \
-    && apk update \
-    && apk add --no-cache \
+    && rpm --import https://repo.almalinux.org/almalinux/RPM-GPG-KEY-AlmaLinux \
+    && dnf install -y 'dnf-command(config-manager)' epel-release \
+    && dnf config-manager --set-enabled powertools \
+    && dnf config-manager --set-enabled epel \
+    && dnf makecache \
+    && dnf install -y \
         $BUILD_DEPS \
         $NGINX_BUILD_DEPS
 
@@ -304,6 +303,13 @@ RUN make deps \
     && make core \
     && make luarocks
 
+RUN set -eux \
+# envsubst
+# ##############################################################################
+    && dnf makecache \
+    && dnf install -y \
+        gettext
+
 ##########################################
 # Combine everything with minimal layers #
 ##########################################
@@ -312,14 +318,14 @@ FROM base
 # http://label-schema.org/rc1/
 LABEL maintainer="Fabio Cicerchia <info@fabiocicerchia.it>" \
     org.label-schema.build-date="${BUILD_DATE}" \
-    org.label-schema.description="Nginx ${VER_NGINX} with Lua support based on alpine (${ARCH}) 3.17.3." \
-    org.label-schema.docker.cmd="docker run -p 80:80 -d ${DOCKER_IMAGE}:${VER_NGINX}-alpine3.17.3" \
+    org.label-schema.description="Nginx ${VER_NGINX} with Lua support based on almalinux (${ARCH}) 8.7-20230222." \
+    org.label-schema.docker.cmd="docker run -p 80:80 -d ${DOCKER_IMAGE}:${VER_NGINX}-almalinux8.7-20230222" \
     org.label-schema.name="${DOCKER_IMAGE}" \
     org.label-schema.schema-version="1.0" \
     org.label-schema.url="https://github.com/${DOCKER_IMAGE}" \
     org.label-schema.vcs-ref=$VCS_REF \
     org.label-schema.vcs-url="https://github.com/${DOCKER_IMAGE}" \
-    org.label-schema.version="${VER_NGINX}-alpine3.17.3" \
+    org.label-schema.version="${VER_NGINX}-almalinux8.7-20230222" \
     image.target.platform="${TARGETPLATFORM}" \
     image.target.os="${TARGETOS}" \
     image.target.arch="${ARCH}" \
@@ -329,7 +335,7 @@ LABEL maintainer="Fabio Cicerchia <info@fabiocicerchia.it>" \
     versions.nginx="${VER_NGINX}" \
     versions.ngx_devel_kit="${VER_NGX_DEVEL_KIT}" \
     versions.njs="${VER_NJS}" \
-    versions.os="3.17.3" \
+    versions.os="8.7-20230222" \
     versions.headers-more-nginx-module="${VER_OPENRESTY_HEADERS}" \
     versions.lua-nginx-module="${VER_LUA_NGINX_MODULE}" \
     versions.lua-resty-cookie="${VER_CLOUDFLARE_COOKIE}" \
@@ -350,13 +356,14 @@ LABEL maintainer="Fabio Cicerchia <info@fabiocicerchia.it>" \
     versions.stream-lua-nginx-module="${VER_OPENRESTY_STREAMLUA}"
 
 ARG PKG_DEPS="\
-        curl \
-        geoip-dev \
-        libxml2-dev \
-        openssl-dev \
-        pcre-dev \
+        GeoIP-devel \
+        ca-certificates \
+        gcc-c++ \
+        libxml2-devel \
+        openssl-devel \
+        pcre-devel \
         unzip \
-        zlib-dev \
+        zlib-devel \
 "
 ENV PKG_DEPS=$PKG_DEPS
 
@@ -366,6 +373,7 @@ COPY --from=builder --chown=101:101 /usr/local/share/lua /usr/local/share/lua
 COPY --from=builder --chown=101:101 /usr/sbin/nginx /usr/sbin/nginx
 COPY --from=builder --chown=101:101 /usr/sbin/nginx-debug /usr/sbin/nginx-debug
 COPY --from=builder --chown=101:101 /var/cache/nginx /var/cache/nginx
+COPY --from=builder --chown=101:101 /usr/bin/envsubst /usr/local/bin/envsubst
 COPY --from=builder --chown=101:101 /usr/local/bin/lua /usr/local/bin/lua
 COPY --from=builder --chown=101:101 /usr/local/bin/luajit /usr/local/bin/luajit
 COPY --from=builder --chown=101:101 /usr/local/bin/luarocks /usr/local/bin/luarocks
@@ -378,116 +386,36 @@ COPY --chown=101:101 tpl/??-*.sh /docker-entrypoint.d/
 COPY --chown=101:101 tpl/nginx.conf /etc/nginx/nginx.conf
 COPY --chown=101:101 tpl/default.conf /etc/nginx/conf.d/default.conf
 
-SHELL ["/bin/ash", "-eo", "pipefail", "-c"]
+SHELL ["/bin/sh", "-o", "pipefail", "-c"]
 
 # hadolint ignore=SC2086
 RUN set -eux \
-    && apk update \
-    && apk add --no-cache --virtual .pkg_deps \
+    && rpm --import https://repo.almalinux.org/almalinux/RPM-GPG-KEY-AlmaLinux \
+    && dnf install -y 'dnf-command(config-manager)' epel-release \
+    && dnf config-manager --set-enabled powertools \
+    && dnf config-manager --set-enabled epel \
+    && dnf makecache \
+    && dnf install -y \
         $PKG_DEPS \
-    && mkdir -p /var/log/nginx
-
-RUN set -x \
-# create nginx user/group first, to be consistent throughout docker variants
-    && addgroup -g 101 -S nginx \
-    && adduser -S -D -H -u 101 -h /var/cache/nginx -s /sbin/nologin -G nginx -g nginx nginx \
-# COMMENTED OUT FROM ORIGINAL DOCKERFILE: https://github.com/nginxinc/docker-nginx/blob/1.23.2/mainline/alpine-slim/Dockerfile
-# REASON: No need to use the existing distributed package as the binary is recompiled.
-#     && apkArch="$(cat /etc/apk/arch)" \
-#     && nginxPackages=" \
-#         nginx=${NGINX_VERSION}-r${PKG_RELEASE} \
-#     " \
-# # install prerequisites for public key and pkg-oss checks
-#     && apk add --no-cache --virtual .checksum-deps \
-#         openssl \
-#     && case "$apkArch" in \
-#         x86_64|aarch64) \
-# # arches officially built by upstream
-#             set -x \
-#             && KEY_SHA512="e09fa32f0a0eab2b879ccbbc4d0e4fb9751486eedda75e35fac65802cc9faa266425edf83e261137a2f4d16281ce2c1a5f4502930fe75154723da014214f0655" \
-#             && wget -O /tmp/nginx_signing.rsa.pub https://nginx.org/keys/nginx_signing.rsa.pub \
-#             && if echo "$KEY_SHA512 */tmp/nginx_signing.rsa.pub" | sha512sum -c -; then \
-#                 echo "key verification succeeded!"; \
-#                 mv /tmp/nginx_signing.rsa.pub /etc/apk/keys/; \
-#             else \
-#                 echo "key verification failed!"; \
-#                 exit 1; \
-#             fi \
-#             && apk add -X "https://nginx.org/packages/mainline/alpine/v$(egrep -o '^[0-9]+\.[0-9]+' /etc/alpine-release)/main" --no-cache $nginxPackages \
-#             ;; \
-#         *) \
-# # we're on an architecture upstream doesn't officially build for
-# # let's build binaries from the published packaging sources
-#             set -x \
-#             && tempDir="$(mktemp -d)" \
-#             && chown nobody:nobody $tempDir \
-#             && apk add --no-cache --virtual .build-deps \
-#                 gcc \
-#                 libc-dev \
-#                 make \
-#                 openssl-dev \
-#                 pcre2-dev \
-#                 zlib-dev \
-#                 linux-headers \
-#                 bash \
-#                 alpine-sdk \
-#                 findutils \
-#             && su nobody -s /bin/sh -c " \
-#                 export HOME=${tempDir} \
-#                 && cd ${tempDir} \
-#                 && curl -f -O https://hg.nginx.org/pkg-oss/archive/${NGINX_VERSION}-${PKG_RELEASE}.tar.gz \
-#                 && PKGOSSCHECKSUM=\"52a80f6c3b3914462f8a0b2fbadea950bcd79c1bd528386aff4c28d5a80c6920d783575a061a47b60fea800eef66bf5a0178a137ea51c37277fe9c2779715990 *${NGINX_VERSION}-${PKG_RELEASE}.tar.gz\" \
-#                 && if [ \"\$(openssl sha512 -r ${NGINX_VERSION}-${PKG_RELEASE}.tar.gz)\" = \"\$PKGOSSCHECKSUM\" ]; then \
-#                     echo \"pkg-oss tarball checksum verification succeeded!\"; \
-#                 else \
-#                     echo \"pkg-oss tarball checksum verification failed!\"; \
-#                     exit 1; \
-#                 fi \
-#                 && tar xzvf ${NGINX_VERSION}-${PKG_RELEASE}.tar.gz \
-#                 && cd pkg-oss-${NGINX_VERSION}-${PKG_RELEASE} \
-#                 && cd alpine \
-#                 && make base \
-#                 && apk index -o ${tempDir}/packages/alpine/${apkArch}/APKINDEX.tar.gz ${tempDir}/packages/alpine/${apkArch}/*.apk \
-#                 && abuild-sign -k ${tempDir}/.abuild/abuild-key.rsa ${tempDir}/packages/alpine/${apkArch}/APKINDEX.tar.gz \
-#                 " \
-#             && cp ${tempDir}/.abuild/abuild-key.rsa.pub /etc/apk/keys/ \
-#             && apk del .build-deps \
-#             && apk add -X ${tempDir}/packages/alpine/ add--no-cache $nginxPackages \
-#             ;; \
-#     esac \
-# # remove checksum deps
-#     && apk del .checksum-deps \
-# # if we have leftovers from building, let's purge them (including extra, unnecessary build deps)
-#     && if [ -n "$tempDir" ]; then rm -rf "$tempDir"; fi \
-#     && if [ -n "/etc/apk/keys/abuild-key.rsa.pub" ]; then rm -f /etc/apk/keys/abuild-key.rsa.pub; fi \
-#     && if [ -n "/etc/apk/keys/nginx_signing.rsa.pub" ]; then rm -f /etc/apk/keys/nginx_signing.rsa.pub; fi \
-# Bring in gettext so we can get `envsubst`, then throw
-# the rest away. To do this, we need to install `gettext`
-# then move `envsubst` out of the way so `gettext` can
-# be deleted completely, then move `envsubst` back.
-    && apk add --no-cache --virtual .gettext gettext \
-    && mv /usr/bin/envsubst /tmp/ \
-    \
-    && runDeps="$( \
-        scanelf --needed --nobanner /tmp/envsubst \
-            | awk '{ gsub(/,/, "\nso:", $2); print "so:" $2 }' \
-            | sort -u \
-            | xargs -r apk info --installed \
-            | sort -u \
-    )" \
-    && apk add --no-cache $runDeps \
-    && apk del .gettext \
-    && mv /tmp/envsubst /usr/local/bin/ \
 # Bring in tzdata so users could set the timezones through the environment
 # variables
-    && apk add --no-cache tzdata \
+    && dnf install -y tzdata \
+# Bring in curl and ca-certificates to make registering on DNS SD easier
+    && dnf install -y curl ca-certificates \
 # forward request and error logs to docker log collector
+    && mkdir -p /var/log/nginx \
     && ln -sf /dev/stdout /var/log/nginx/access.log \
-    && ln -sf /dev/stderr /var/log/nginx/error.log
-
+    && ln -sf /dev/stderr /var/log/nginx/error.log \
+# create nginx user/group first, to be consistent throughout docker variants
+    && groupadd --system --gid 101 nginx \
+    && useradd --system --gid nginx --no-create-home --home /nonexistent --comment "nginx user" --shell /bin/false --uid 101 nginx \
 # Upgrade software to latest version
 # ##############################################################################
-RUN apk upgrade
+    && dnf upgrade -y \
+# Cleanup
+# ##############################################################################
+    && dnf clean all \
+    && rm -rf /var/cache/dnf
 
 # smoke test
 # ##############################################################################
