Automated updates

diff --git a/nginx/1.23.1/amazonlinux/2/Dockerfile b/nginx/1.23.1/amazonlinux/2/Dockerfile
--- a/nginx/1.23.1/amazonlinux/2/Dockerfile
+++ b/nginx/1.23.1/amazonlinux/2/Dockerfile
@@ -8,8 +8,8 @@
 # Repo: https://github.com/fabiocicerchia/nginx-lua
 
 ARG ARCH=
-ARG DISTRO=alpine
-ARG DISTRO_VER=3.16.0
+ARG DISTRO=amazonlinux
+ARG DISTRO_VER=2
 
 #############################
 # Settings Common Variables #
@@ -29,7 +29,7 @@ ARG VCS_REF
 ENV VCS_REF=$VCS_REF
 
 # lua
-ARG VER_LUA=5.4.3
+ARG VER_LUA=54
 ENV VER_LUA=$VER_LUA
 
 # ngx_devel_kit
@@ -41,26 +41,27 @@ ENV VER_NGX_DEVEL_KIT=$VER_NGX_DEVEL_KIT
 # luajit2
 # https://github.com/openresty/luajit2/tags
 # Note: LuaJIT2 is stuck on Lua 5.1 since 2009.
-ARG VER_LUAJIT=2.1-20220310
+ARG VER_LUAJIT=2.1-20220411
 ENV VER_LUAJIT=$VER_LUAJIT
 ARG LUAJIT_LIB=/usr/local/lib
 ENV LUAJIT_LIB=$LUAJIT_LIB
 ARG LUAJIT_INC=/usr/local/include/luajit-2.1
 ENV LUAJIT_INC=$LUAJIT_INC
-ENV LUA_INCDIR=$LUAJIT_INC
 ARG LD_LIBRARY_PATH=/usr/local/lib/:$LD_LIBRARY_PATH
 ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH
 
 # lua-nginx-module
 # https://github.com/openresty/lua-nginx-module/tags
 # Production ready.
-ARG VER_LUA_NGINX_MODULE=0.10.20
+# TODO: Restore to 0.10.xx as the v0.10.21 has a bug fixed in commit b6d167cf1a93c0c885c28db5a439f2404874cb26
+ARG VER_LUA_NGINX_MODULE=cff86dd7f677e3b856fb7ca1de90746b24eb6411
 ENV VER_LUA_NGINX_MODULE=$VER_LUA_NGINX_MODULE
 
 # lua-resty-core
 # https://github.com/openresty/lua-resty-core/tags
 # This library is production ready.
-ARG VER_LUA_RESTY_CORE=0.1.22
+# TODO: Restore to 0.1.xx as the v0.1.23 has a bug fixed in commit 79f520183bb5b1a278d8a8be3f53659737232253
+ARG VER_LUA_RESTY_CORE=79f520183bb5b1a278d8a8be3f53659737232253
 ENV VER_LUA_RESTY_CORE=$VER_LUA_RESTY_CORE
 ARG LUA_LIB_DIR=/usr/local/share/lua/5.4
 ENV LUA_LIB_DIR=$LUA_LIB_DIR
@@ -68,12 +69,12 @@ ENV LUA_LIB_DIR=$LUA_LIB_DIR
 # lua-resty-lrucache
 # https://github.com/openresty/lua-resty-lrucache/tags
 # This library is considered production ready.
-ARG VER_LUA_RESTY_LRUCACHE=0.11
+ARG VER_LUA_RESTY_LRUCACHE=0.13
 ENV VER_LUA_RESTY_LRUCACHE=$VER_LUA_RESTY_LRUCACHE
 
 # headers-more-nginx-module
-# https://github.com/openresty/headers-more-nginx-module/commits/master
-ARG VER_OPENRESTY_HEADERS=a4a0686605161a6777d7d612d5aef79b9e7c13e0
+# https://github.com/openresty/headers-more-nginx-module/tags
+ARG VER_OPENRESTY_HEADERS=0.34
 ENV VER_OPENRESTY_HEADERS=$VER_OPENRESTY_HEADERS
 
 # lua-resty-cookie
@@ -88,12 +89,12 @@ ENV VER_OPENRESTY_DNS=$VER_OPENRESTY_DNS
 
 # lua-resty-memcached
 # https://github.com/openresty/lua-resty-memcached/tags
-ARG VER_OPENRESTY_MEMCACHED=0.16
+ARG VER_OPENRESTY_MEMCACHED=0.17
 ENV VER_OPENRESTY_MEMCACHED=$VER_OPENRESTY_MEMCACHED
 
 # lua-resty-mysql
 # https://github.com/openresty/lua-resty-mysql/tags
-ARG VER_OPENRESTY_MYSQL=0.24
+ARG VER_OPENRESTY_MYSQL=0.25
 ENV VER_OPENRESTY_MYSQL=$VER_OPENRESTY_MYSQL
 
 # lua-resty-redis
@@ -123,12 +124,12 @@ ENV VER_OPENRESTY_HEALTHCHECK=$VER_OPENRESTY_HEALTHCHECK
 
 # lua-resty-websocket
 # https://github.com/openresty/lua-resty-websocket/tags
-ARG VER_OPENRESTY_WEBSOCKET=0.08
+ARG VER_OPENRESTY_WEBSOCKET=0.09
 ENV VER_OPENRESTY_WEBSOCKET=$VER_OPENRESTY_WEBSOCKET
 
 # lua-rocks
 # https://luarocks.github.io/luarocks/releases/
-ARG VER_LUAROCKS=3.8.0
+ARG VER_LUAROCKS=3.9.1
 ENV VER_LUAROCKS=$VER_LUAROCKS
 
 # lua-upstream-nginx-module
@@ -138,16 +139,17 @@ ENV VER_LUA_UPSTREAM=$VER_LUA_UPSTREAM
 
 # nginx-lua-prometheus
 # https://github.com/knyar/nginx-lua-prometheus/tags
-ARG VER_PROMETHEUS=0.20220127
+ARG VER_PROMETHEUS=0.20220527
 ENV VER_PROMETHEUS=$VER_PROMETHEUS
 
 # stream-lua-nginx-module
-# https://github.com/openresty/stream-lua-nginx-module/tags
-ARG VER_OPENRESTY_STREAMLUA=0.0.10
+# https://github.com/openresty/stream-lua-nginx-module/commits/master
+# TODO: Restore to 0.0.xx as the v0.0.11 has a bug fixed in commit 9ce0848cff7c3c5eb0a7d5adfe2de22ea98e1e63
+ARG VER_OPENRESTY_STREAMLUA=9ce0848cff7c3c5eb0a7d5adfe2de22ea98e1e63
 ENV VER_OPENRESTY_STREAMLUA=$VER_OPENRESTY_STREAMLUA
 
 # https://github.com/nginx/nginx/releases
-ARG VER_NGINX=1.21.6
+ARG VER_NGINX=1.23.1
 ENV VER_NGINX=$VER_NGINX
 # References:
 #  - https://developers.redhat.com/blog/2018/03/21/compiler-and-linker-flags-gcc
@@ -224,40 +226,32 @@ ARG NGINX_BUILD_CONFIG="\
 ENV NGINX_BUILD_CONFIG=$NGINX_BUILD_CONFIG
 
 ARG BUILD_DEPS_BASE="\
-        curl \
-        geoip-dev \
+        GeoIP-devel \
+        ca-certificates \
+        gcc-c++ \
         gzip \
+        lua${VER_LUA} \
+        lua${VER_LUA}-devel \
         make \
-        openssl-dev \
+        openssl-devel \
         patch \
-        pcre-dev \
+        pcre-devel \
         tar \
-        zlib-dev \
+        unzip \
+        zlib-devel \
 "
 ENV BUILD_DEPS_BASE=$BUILD_DEPS_BASE
 ARG BUILD_DEPS_AMD64="\
         ${BUILD_DEPS_BASE} \
-        g++ \
 "
 ENV BUILD_DEPS_AMD64=$BUILD_DEPS_AMD64
 ARG BUILD_DEPS_ARM64V8="\
         ${BUILD_DEPS_BASE} \
-        gcc-aarch64-none-elf \
 "
 ENV BUILD_DEPS_ARM64V8=$BUILD_DEPS_ARM64V8
 ENV BUILD_DEPS=
 
-ARG NGINX_BUILD_DEPS="\
-# NGINX
-        alpine-sdk \
-        bash \
-        findutils \
-        gd-dev \
-        libedit-dev \
-        libxslt-dev \
-        linux-headers \
-        perl-dev \
-"
+ARG NGINX_BUILD_DEPS=""
 ENV NGINX_BUILD_DEPS=$NGINX_BUILD_DEPS
 
 ####################################
@@ -268,17 +262,27 @@ FROM base AS builder
 # hadolint ignore=SC2086
 RUN set -eux \
     && eval BUILD_DEPS="\$$(echo BUILD_DEPS_${ARCH} | tr '[:lower:]' '[:upper:]')" \
-    && apk update \
-    && apk add --no-cache \
+    && yum makecache \
+    && yum install -y \
         $BUILD_DEPS \
-        $NGINX_BUILD_DEPS
+        $NGINX_BUILD_DEPS \
+    && yum clean all \
+    && rm -rf /var/cache/yum
 
 COPY tpl/Makefile Makefile
 
 RUN make deps \
-    && make lua-src \
     && make core \
     && make luarocks
+
+RUN set -eux \
+# envsubst
+# ##############################################################################
+    && yum makecache \
+    && yum install -y \
+        gettext \
+    && yum clean all \
+    && rm -rf /var/cache/yum
 
 ##########################################
 # Combine everything with minimal layers #
@@ -324,11 +328,14 @@ LABEL maintainer="Fabio Cicerchia <info@fabiocicerchia.it>" \
     versions.stream-lua-nginx-module="${VER_OPENRESTY_STREAMLUA}"
 
 ARG PKG_DEPS="\
-        geoip-dev \
-        openssl-dev \
-        pcre-dev \
+        GeoIP-devel \
+        ca-certificates \
+        lua${VER_LUA} \
+        lua${VER_LUA}-devel \
+        openssl-devel \
+        pcre-devel \
         unzip \
-        zlib-dev \
+        zlib-devel \
 "
 ENV PKG_DEPS=$PKG_DEPS
 
@@ -338,11 +345,9 @@ COPY --from=builder --chown=101:101 /usr/local/share/lua /usr/local/share/lua
 COPY --from=builder --chown=101:101 /usr/sbin/nginx /usr/sbin/nginx
 COPY --from=builder --chown=101:101 /usr/sbin/nginx-debug /usr/sbin/nginx-debug
 COPY --from=builder --chown=101:101 /var/cache/nginx /var/cache/nginx
-COPY --from=builder --chown=101:101 /usr/local/bin/lua /usr/local/bin/lua
-COPY --from=builder --chown=101:101 /usr/local/bin/luajit /usr/local/bin/luajit
+COPY --from=builder --chown=101:101 /usr/bin/envsubst /usr/local/bin/envsubst
 COPY --from=builder --chown=101:101 /usr/local/bin/luarocks /usr/local/bin/luarocks
 COPY --from=builder --chown=101:101 /usr/local/etc/luarocks /usr/local/etc/luarocks
-COPY --from=builder --chown=101:101 $LUAJIT_INC $LUAJIT_INC
 
 COPY --chown=101:101 tpl/support.sh /
 COPY --chown=101:101 tpl/docker-entrypoint.sh /
@@ -351,44 +356,37 @@ COPY --chown=101:101 tpl/20-envsubst-on-templates.sh /docker-entrypoint.d/
 COPY --chown=101:101 tpl/nginx.conf /etc/nginx/nginx.conf
 COPY --chown=101:101 tpl/default.conf /etc/nginx/conf.d/default.conf
 
-SHELL ["/bin/ash", "-eo", "pipefail", "-c"]
+SHELL ["/bin/sh", "-o", "pipefail", "-c"]
 
 # hadolint ignore=SC2086
 RUN set -eux \
-    && apk update \
-    && apk add --no-cache --virtual .pkg_deps \
+    && yum makecache \
+    && yum install -y \
         $PKG_DEPS \
-# Bring in gettext so we can get `envsubst`, then throw
-# the rest away. To do this, we need to install `gettext`
-# then move `envsubst` out of the way so `gettext` can
-# be deleted completely, then move `envsubst` back.
-    && apk add --no-cache --virtual .gettext gettext \
-    && mv /usr/bin/envsubst /tmp/ \
-    && runDeps="$( \
-        scanelf --needed --nobanner /tmp/envsubst \
-            | awk '{ gsub(/,/, "\nso:", $2); print "so:" $2 }' \
-            | sort -u \
-            | xargs -r apk info --installed \
-            | sort -u \
-    )" \
-    && apk add --no-cache --virtual .run_deps $runDeps \
-    && apk del .gettext \
-    && mv /tmp/envsubst /usr/local/bin/ \
+        shadow-utils \
+# Fix LUA alias
+    && ln -sf /usr/bin/lua${VER_LUA} /usr/local/bin/lua \
 # Bring in tzdata so users could set the timezones through the environment
 # variables
-    && apk add --no-cache --virtual pkg_tz tzdata \
+    && yum install -y tzdata \
 # Bring in curl and ca-certificates to make registering on DNS SD easier
-    && apk add --no-cache --virtual pkg_dns curl ca-certificates \
+    && yum install -y curl ca-certificates \
 # forward request and error logs to docker log collector
     && mkdir -p /var/log/nginx \
     && ln -sf /dev/stdout /var/log/nginx/access.log \
     && ln -sf /dev/stderr /var/log/nginx/error.log \
 # create nginx user/group first, to be consistent throughout docker variants
-    && addgroup -g 101 -S nginx \
-    && adduser -S -D -H -u 101 -h /var/cache/nginx -s /sbin/nologin -G nginx -g nginx nginx \
+    && groupadd --system --gid 101 nginx \
+    && useradd --system --gid nginx --no-create-home --home /nonexistent --comment "nginx user" --shell /bin/false --uid 101 nginx \
 # Upgrade software to latest version
 # ##############################################################################
-    && apk upgrade
+    && yum upgrade -y \
+# Cleanup
+# ##############################################################################
+    && yum remove -y \
+        shadow-utils \
+    && yum clean all \
+    && rm -rf /var/cache/yum
 
 # smoke test
 # ##############################################################################
