Automated updates

diff --git a/nginx/1.27.0/debian/12.6/Dockerfile b/nginx/1.27.0/debian/12.6/Dockerfile
--- a/nginx/1.27.0/debian/12.6/Dockerfile
+++ b/nginx/1.27.0/debian/12.6/Dockerfile
@@ -8,8 +8,8 @@
 # Repo: https://github.com/fabiocicerchia/nginx-lua
 
 ARG ARCH=
-ARG DISTRO=amazonlinux
-ARG DISTRO_VER=2023.5.20240624.0
+ARG DISTRO=debian
+ARG DISTRO_VER=12.6
 
 #############################
 # Settings Common Variables #
@@ -211,7 +211,7 @@ ENV VER_OPENRESTY_STRING=$VER_OPENRESTY_STRING
 # Replicate same official env variable
 ENV NGINX_VERSION   $VER_NGINX
 ENV NJS_VERSION     $VER_NJS
-ENV PKG_RELEASE     1
+ENV PKG_RELEASE     1~$DISTRO_VER
 
 # References:
 #  - https://developers.redhat.com/blog/2018/03/21/compiler-and-linker-flags-gcc
@@ -296,19 +296,17 @@ ENV NGINX_BUILD_CONFIG=$NGINX_BUILD_CONFIG
 
 ARG BUILD_DEPS_BASE="\
         ca-certificates \
-        gcc-c++ \
-        gzip \
-        libmaxminddb-devel \
-        libxml2-devel \
-        libxslt-devel \
+        curl \
+        g++ \
+        libmaxminddb-dev \
+        libpcre3-dev \
+        libssl-dev \
+        libxml2-dev \
+        libxslt1-dev \
         make \
-        openssl-devel \
         patch \
-        pcre-devel \
-        tar \
         unzip \
-        which \
-        zlib-devel \
+        zlib1g-dev \
 "
 ENV BUILD_DEPS_BASE=$BUILD_DEPS_BASE
 ARG BUILD_DEPS_AMD64="\
@@ -327,6 +325,8 @@ ARG NGINX_BUILD_DEPS="\
 "
 ENV NGINX_BUILD_DEPS=$NGINX_BUILD_DEPS
 
+ENV DEBIAN_FRONTEND noninteractive
+
 ####################################
 # Build Nginx with support for LUA #
 ####################################
@@ -335,12 +335,13 @@ FROM base AS builder
 # hadolint ignore=SC2086
 RUN set -eux \
     && eval BUILD_DEPS="\$$(echo BUILD_DEPS_${ARCH} | tr '[:lower:]' '[:upper:]')" \
-    && yum makecache \
-    && yum install -y \
+    && apt-get update \
+    && apt-get install -y --no-install-recommends --no-install-suggests \
+        apt-utils \
+    && apt-get install -y --no-install-recommends --no-install-suggests \
         $BUILD_DEPS \
         $NGINX_BUILD_DEPS \
-    && yum clean all \
-    && rm -rf /var/cache/yum
+    && rm -rf /var/lib/apt/lists/*
 
 COPY tpl/Makefile Makefile
 COPY tpl/patches patches
@@ -348,15 +349,6 @@ COPY tpl/patches patches
 RUN make deps \
     && make core \
     && make luarocks
-
-RUN set -eux \
-# envsubst
-# ##############################################################################
-    && yum makecache \
-    && yum install -y \
-        gettext \
-    && yum clean all \
-    && rm -rf /var/cache/yum
 
 ##########################################
 # Combine everything with minimal layers #
@@ -366,18 +358,18 @@ FROM base
 # http://label-schema.org/rc1/
 LABEL maintainer="Fabio Cicerchia <info@fabiocicerchia.it>" \
     org.label-schema.build-date="${BUILD_DATE}" \
-    org.label-schema.description="Nginx ${VER_NGINX} with Lua support based on amazonlinux (${ARCH}) 2023.5.20240624.0." \
-    org.label-schema.docker.cmd="docker run -p 80:80 -d ${DOCKER_IMAGE}:${VER_NGINX}-amazonlinux2023.5.20240624.0" \
+    org.label-schema.description="Nginx ${VER_NGINX} with Lua support based on debian (${ARCH}) 12.6." \
+    org.label-schema.docker.cmd="docker run -p 80:80 -d ${DOCKER_IMAGE}:${VER_NGINX}-debian12.6" \
     org.label-schema.name="${DOCKER_IMAGE}" \
     org.label-schema.schema-version="1.0" \
     org.label-schema.url="https://github.com/${DOCKER_IMAGE}" \
     org.label-schema.vcs-ref=$VCS_REF \
     org.label-schema.vcs-url="https://github.com/${DOCKER_IMAGE}" \
-    org.label-schema.version="${VER_NGINX}-amazonlinux2023.5.20240624.0" \
+    org.label-schema.version="${VER_NGINX}-debian12.6" \
     image.target.platform="${TARGETPLATFORM}" \
     image.target.os="${TARGETOS}" \
     image.target.arch="${ARCH}" \
-    versions.os="2023.5.20240624.0" \
+    versions.os="12.6" \
     versions.luajit2="${VER_LUAJIT}" \
     versions.luarocks="${VER_LUAROCKS}" \
     versions.nginx="${VER_NGINX}" \
@@ -410,17 +402,16 @@ LABEL maintainer="Fabio Cicerchia <info@fabiocicerchia.it>" \
 
 ARG PKG_DEPS="\
         ca-certificates \
-        libxml2-devel \
-        openssl-devel \
-        pcre-devel \
+        libmaxminddb-dev \
+        libpcre3-dev \
+        libssl-dev \
+        libxml2-dev \
         unzip \
-        zlib-devel \
+        zlib1g-dev \
 "
 ENV PKG_DEPS=$PKG_DEPS
 
 COPY --from=builder --chown=101:101 /etc/nginx /etc/nginx
-COPY --from=builder --chown=101:101 /usr/bin/envsubst /usr/local/bin/envsubst
-COPY --from=builder --chown=101:101 /usr/lib64 /usr/lib64
 COPY --from=builder --chown=101:101 /usr/local/lib /usr/local/lib
 COPY --from=builder --chown=101:101 /usr/local/share/lua /usr/local/share/lua
 COPY --from=builder --chown=101:101 /usr/sbin/nginx /usr/sbin/nginx
@@ -444,43 +435,126 @@ COPY --chown=101:101 tpl/docker-entrypoint.sh /
 COPY --chown=101:101 tpl/nginx.conf /etc/nginx/nginx.conf
 COPY --chown=101:101 tpl/support.sh /
 
-SHELL ["/bin/sh", "-o", "pipefail", "-c"]
+SHELL ["/bin/bash", "-o", "pipefail", "-c"]
 
 # hadolint ignore=SC2086
 RUN set -eux \
-    && yum makecache \
-    && yum install -y \
+    && apt-get update \
+    && apt-get install -y --no-install-recommends --no-install-suggests \
         $PKG_DEPS \
-        shadow-utils \
-# Fix LUA alias
-    && ln -sf /usr/local/bin/luajit /usr/local/bin/lua \
-# Bring in tzdata so users could set the timezones through the environment
-# variables
-    && yum install -y tzdata \
-# Bring in curl and ca-certificates to make registering on DNS SD easier
-    && yum install -y --allowerasing curl ca-certificates \
-# forward request and error logs to docker log collector
+    && rm -rf /var/lib/apt/lists/* \
     && mkdir -p /var/log/nginx \
-    && ln -sf /dev/stdout /var/log/nginx/access.log \
-    && ln -sf /dev/stderr /var/log/nginx/error.log \
+# Fix LUA alias
+    && ln -sf /usr/local/bin/luajit /usr/local/bin/lua
+
+RUN set -x \
 # create nginx user/group first, to be consistent throughout docker variants
-    && groupadd --system --gid 101 nginx \
-    && useradd --system --gid nginx --no-create-home --home /nonexistent --comment "nginx user" --shell /bin/false --uid 101 nginx \
+    && addgroup --system --gid 101 nginx \
+    && adduser --system --disabled-login --ingroup nginx --no-create-home --home /nonexistent --gecos "nginx user" --shell /bin/false --uid 101 nginx \
+    && apt-get update \
+    && apt-get install --no-install-recommends --no-install-suggests -y gnupg1 ca-certificates \
+# COMMENTED OUT FROM ORIGINAL DOCKERFILE: https://github.com/nginxinc/docker-nginx/blob/1.23.2/mainline/debian/Dockerfile
+# REASON: No need to use the existing distributed package as the binary is recompiled.
+#     && \
+#     NGINX_GPGKEY=573BFD6B3D8FBC641079A6ABABF5BD827BD9BF62; \
+#     NGINX_GPGKEY_PATH=/usr/share/keyrings/nginx-archive-keyring.gpg; \
+#     export GNUPGHOME="$(mktemp -d)"; \
+#     found=''; \
+#     for server in \
+#         hkp://keyserver.ubuntu.com:80 \
+#         pgp.mit.edu \
+#     ; do \
+#         echo "Fetching GPG key $NGINX_GPGKEY from $server"; \
+#         gpg1 --keyserver "$server" --keyserver-options timeout=10 --recv-keys "$NGINX_GPGKEY" && found=yes && break; \
+#     done; \
+#     test -z "$found" && echo >&2 "error: failed to fetch GPG key $NGINX_GPGKEY" && exit 1; \
+#     gpg1 --export "$NGINX_GPGKEY" > "$NGINX_GPGKEY_PATH" ; \
+#     rm -rf "$GNUPGHOME"; \
+#     apt-get remove --purge --auto-remove -y gnupg1 && rm -rf /var/lib/apt/lists/* \
+#     && dpkgArch="$(dpkg --print-architecture)" \
+#     && nginxPackages=" \
+#         nginx=${NGINX_VERSION}-${PKG_RELEASE} \
+#         nginx-module-xslt=${NGINX_VERSION}-${PKG_RELEASE} \
+#         nginx-module-geoip=${NGINX_VERSION}-${PKG_RELEASE} \
+#         nginx-module-image-filter=${NGINX_VERSION}-${PKG_RELEASE} \
+#         nginx-module-njs=${NGINX_VERSION}+${NJS_VERSION}-${PKG_RELEASE} \
+#     " \
+#     && case "$dpkgArch" in \
+#         amd64|arm64) \
+# # arches officialy built by upstream
+#             echo "deb [signed-by=$NGINX_GPGKEY_PATH] https://nginx.org/packages/mainline/debian/ bullseye nginx" >> /etc/apt/sources.list.d/nginx.list \
+#             && apt-get update \
+#             ;; \
+#         *) \
+# # we're on an architecture upstream doesn't officially build for
+# # let's build binaries from the published source packages
+#             echo "deb-src [signed-by=$NGINX_GPGKEY_PATH] https://nginx.org/packages/mainline/debian/ bullseye nginx" >> /etc/apt/sources.list.d/nginx.list \
+#             \
+# # new directory for storing sources and .deb files
+#             && tempDir="$(mktemp -d)" \
+#             && chmod 777 "$tempDir" \
+# # (777 to ensure APT's "_apt" user can access it too)
+#             \
+# # save list of currently-installed packages so build dependencies can be cleanly removed later
+#             && savedAptMark="$(apt-mark showmanual)" \
+#             \
+# # build .deb files from upstream's source packages (which are verified by apt-get)
+#             && apt-get update \
+#             && apt-get build-dep -y $nginxPackages \
+#             && ( \
+#                 cd "$tempDir" \
+#                 && DEB_BUILD_OPTIONS="nocheck parallel=$(nproc)" \
+#                     apt-get source --compile $nginxPackages \
+#             ) \
+# # we don't remove APT lists here because they get re-downloaded and removed later
+#             \
+# # reset apt-mark's "manual" list so that "purge --auto-remove" will remove all build dependencies
+# # (which is done after we install the built packages so we don't have to redownload any overlapping dependencies)
+#             && apt-mark showmanual | xargs apt-mark auto > /dev/null \
+#             && { [ -z "$savedAptMark" ] || apt-mark manual $savedAptMark; } \
+#             \
+# # create a temporary local APT repo to install from (so that dependency resolution can be handled by APT, as it should be)
+#             && ls -lAFh "$tempDir" \
+#             && ( cd "$tempDir" && dpkg-scanpackages . > Packages ) \
+#             && grep '^Package: ' "$tempDir/Packages" \
+#             && echo "deb [ trusted=yes ] file://$tempDir ./" > /etc/apt/sources.list.d/temp.list \
+# # work around the following APT issue by using "Acquire::GzipIndexes=false" (overriding "/etc/apt/apt.conf.d/docker-gzip-indexes")
+# #   Could not open file /var/lib/apt/lists/partial/_tmp_tmp.ODWljpQfkE_._Packages - open (13: Permission denied)
+# #   ...
+# #   E: Failed to fetch store:/var/lib/apt/lists/partial/_tmp_tmp.ODWljpQfkE_._Packages  Could not open file /var/lib/apt/lists/partial/_tmp_tmp.ODWljpQfkE_._Packages - open (13: Permission denied)
+#             && apt-get -o Acquire::GzipIndexes=false update \
+#             ;; \
+#     esac \
+#     \
+    && apt-get install --no-install-recommends --no-install-suggests -y \
+#                         $nginxPackages \
+                        gettext-base \
+                        curl \
+    && apt-get remove --purge --auto-remove -y && rm -rf /var/lib/apt/lists/* /etc/apt/sources.list.d/nginx.list \
+    \
+# if we have leftovers from building, let's purge them (including extra, unnecessary build deps)
+#    && if [ -n "$tempDir" ]; then \
+#        apt-get purge -y --auto-remove \
+#        && rm -rf "$tempDir" /etc/apt/sources.list.d/temp.list; \
+#    fi \
+# forward request and error logs to docker log collector
+    && ln -sf /dev/stdout /var/log/nginx/access.log \
+    && ln -sf /dev/stderr /var/log/nginx/error.log
+
 # Upgrade software to latest version
 # ##############################################################################
-    && yum upgrade -y \
+RUN apt-get upgrade -y \
 # Cleanup
 # ##############################################################################
-    && yum remove -y \
-        shadow-utils \
-    && yum clean all \
-    && rm -rf /var/cache/yum
+    && apt-get autoremove -y \
+    && rm -rf /var/lib/apt/lists/*
 
 # smoke test
 # ##############################################################################
 RUN envsubst -V \
     && nginx -V \
     && nginx -t \
+    && luajit -v \
     && lua -v \
     && luarocks --version
 
