sync with official dockerfile + add missing njs

diff --git a/nginx/1.23.3/debian/11.6/Dockerfile-compat b/nginx/1.23.3/debian/11.6/Dockerfile-compat
--- a/nginx/1.23.3/debian/11.6/Dockerfile-compat
+++ b/nginx/1.23.3/debian/11.6/Dockerfile-compat
@@ -155,6 +155,16 @@ ENV VER_OPENRESTY_STREAMLUA=$VER_OPENRESTY_STREAMLUA
 # https://github.com/nginx/nginx/releases
 ARG VER_NGINX=1.23.3
 ENV VER_NGINX=$VER_NGINX
+
+# https://github.com/nginx/njs
+ARG VER_NJS=0.7.10
+ENV VER_NJS=$VER_NJS
+
+# Replicate same official env variable
+ENV NGINX_VERSION   $VER_NGINX
+ENV NJS_VERSION     $VER_NJS
+ENV PKG_RELEASE     1~$DISTRO_VER
+
 # References:
 #  - https://developers.redhat.com/blog/2018/03/21/compiler-and-linker-flags-gcc
 #  - https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html
@@ -165,6 +175,7 @@ ENV VER_NGINX=$VER_NGINX
 # -Werror=format-security   Reject potentially unsafe format string arguents
 # -Wp,-D_FORTIFY_SOURCE=2   Run-time buffer overflow detection
 # -fPIC                     No text relocations
+# ORIGINAL VALUE: -g -O2 -ffile-prefix-map=/data/builder/debuild/nginx-1.23.3/debian/debuild-base/nginx-1.23.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fPIC
 ARG NGX_CFLAGS="-g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fPIC"
 ENV NGX_CFLAGS=$NGX_CFLAGS
 # References
@@ -177,6 +188,7 @@ ENV NGX_CFLAGS=$NGX_CFLAGS
 # -Wl,-z,now                  Disable lazy binding
 # -Wl,--as-needed             Only link with needed libraries
 # -pie                        Full ASLR for executables
+# ORIGINAL VALUE: -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -pie
 ARG NGX_LDOPT="-Wl,-rpath,/usr/local/lib -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -pie"
 ENV NGX_LDOPT=$NGX_LDOPT
 # Reference: http://nginx.org/en/docs/configure.html
@@ -221,6 +233,7 @@ ARG NGINX_BUILD_CONFIG="\
             --with-stream_realip_module \
             --with-stream_ssl_module \
             --with-stream_ssl_preread_module \
+            --add-module=/njs-${VER_NJS}/nginx \
             --add-module=/lua-nginx-module-${VER_LUA_NGINX_MODULE} \
             --add-module=/ngx_devel_kit-${VER_NGX_DEVEL_KIT} \
             --add-module=/lua-upstream-nginx-module-${VER_LUA_UPSTREAM} \
@@ -281,14 +294,6 @@ RUN make deps \
     && make core \
     && make luarocks
 
-RUN set -eux \
-# envsubst
-# ##############################################################################
-    && apt-get update \
-    && apt-get install -y --no-install-recommends --no-install-suggests \
-        gettext-base \
-    && rm -rf /var/lib/apt/lists/*
-
 ##########################################
 # Combine everything with minimal layers #
 ##########################################
@@ -313,6 +318,7 @@ LABEL maintainer="Fabio Cicerchia <info@fabiocicerchia.it>" \
     versions.luarocks="${VER_LUAROCKS}" \
     versions.nginx="${VER_NGINX}" \
     versions.ngx_devel_kit="${VER_NGX_DEVEL_KIT}" \
+    versions.njs="${VER_NJS}" \
     versions.os="11.6" \
     versions.headers-more-nginx-module="${VER_OPENRESTY_HEADERS}" \
     versions.lua-nginx-module="${VER_LUA_NGINX_MODULE}" \
@@ -349,7 +355,6 @@ COPY --from=builder --chown=101:101 /usr/local/share/lua /usr/local/share/lua
 COPY --from=builder --chown=101:101 /usr/sbin/nginx /usr/sbin/nginx
 COPY --from=builder --chown=101:101 /usr/sbin/nginx-debug /usr/sbin/nginx-debug
 COPY --from=builder --chown=101:101 /var/cache/nginx /var/cache/nginx
-COPY --from=builder --chown=101:101 /usr/bin/envsubst /usr/local/bin/envsubst
 COPY --from=builder --chown=101:101 /usr/local/bin/lua /usr/local/bin/lua
 COPY --from=builder --chown=101:101 /usr/local/bin/luajit /usr/local/bin/luajit
 COPY --from=builder --chown=101:101 /usr/local/bin/luarocks /usr/local/bin/luarocks
@@ -369,21 +374,108 @@ RUN set -eux \
     && apt-get update \
     && apt-get install -y --no-install-recommends --no-install-suggests \
         $PKG_DEPS \
-# Bring in tzdata so users could set the timezones through the environment
-# variables
-    && apt-get install -y --no-install-recommends --no-install-suggests tzdata \
-# Bring in curl and ca-certificates to make registering on DNS SD easier
-    && apt-get install -y --no-install-recommends --no-install-suggests curl ca-certificates \
-# forward request and error logs to docker log collector
-    && mkdir -p /var/log/nginx \
-    && ln -sf /dev/stdout /var/log/nginx/access.log \
-    && ln -sf /dev/stderr /var/log/nginx/error.log \
+    && rm -rf /var/lib/apt/lists/* \
+    && mkdir -p /var/log/nginx
+
+RUN set -x \
 # create nginx user/group first, to be consistent throughout docker variants
     && addgroup --system --gid 101 nginx \
     && adduser --system --disabled-login --ingroup nginx --no-create-home --home /nonexistent --gecos "nginx user" --shell /bin/false --uid 101 nginx \
+    && apt-get update \
+    && apt-get install --no-install-recommends --no-install-suggests -y gnupg1 ca-certificates \
+# COMMENTED OUT FROM ORIGINAL DOCKERFILE: https://github.com/nginxinc/docker-nginx/blob/1.23.2/mainline/debian/Dockerfile
+# REASON: No need to use the existing distributed package as the binary is recompiled.
+#     && \
+#     NGINX_GPGKEY=573BFD6B3D8FBC641079A6ABABF5BD827BD9BF62; \
+#     NGINX_GPGKEY_PATH=/usr/share/keyrings/nginx-archive-keyring.gpg; \
+#     export GNUPGHOME="$(mktemp -d)"; \
+#     found=''; \
+#     for server in \
+#         hkp://keyserver.ubuntu.com:80 \
+#         pgp.mit.edu \
+#     ; do \
+#         echo "Fetching GPG key $NGINX_GPGKEY from $server"; \
+#         gpg1 --keyserver "$server" --keyserver-options timeout=10 --recv-keys "$NGINX_GPGKEY" && found=yes && break; \
+#     done; \
+#     test -z "$found" && echo >&2 "error: failed to fetch GPG key $NGINX_GPGKEY" && exit 1; \
+#     gpg1 --export "$NGINX_GPGKEY" > "$NGINX_GPGKEY_PATH" ; \
+#     rm -rf "$GNUPGHOME"; \
+#     apt-get remove --purge --auto-remove -y gnupg1 && rm -rf /var/lib/apt/lists/* \
+#     && dpkgArch="$(dpkg --print-architecture)" \
+#     && nginxPackages=" \
+#         nginx=${NGINX_VERSION}-${PKG_RELEASE} \
+#         nginx-module-xslt=${NGINX_VERSION}-${PKG_RELEASE} \
+#         nginx-module-geoip=${NGINX_VERSION}-${PKG_RELEASE} \
+#         nginx-module-image-filter=${NGINX_VERSION}-${PKG_RELEASE} \
+#         nginx-module-njs=${NGINX_VERSION}+${NJS_VERSION}-${PKG_RELEASE} \
+#     " \
+#     && case "$dpkgArch" in \
+#         amd64|arm64) \
+# # arches officialy built by upstream
+#             echo "deb [signed-by=$NGINX_GPGKEY_PATH] https://nginx.org/packages/mainline/debian/ bullseye nginx" >> /etc/apt/sources.list.d/nginx.list \
+#             && apt-get update \
+#             ;; \
+#         *) \
+# # we're on an architecture upstream doesn't officially build for
+# # let's build binaries from the published source packages
+#             echo "deb-src [signed-by=$NGINX_GPGKEY_PATH] https://nginx.org/packages/mainline/debian/ bullseye nginx" >> /etc/apt/sources.list.d/nginx.list \
+#             \
+# # new directory for storing sources and .deb files
+#             && tempDir="$(mktemp -d)" \
+#             && chmod 777 "$tempDir" \
+# # (777 to ensure APT's "_apt" user can access it too)
+#             \
+# # save list of currently-installed packages so build dependencies can be cleanly removed later
+#             && savedAptMark="$(apt-mark showmanual)" \
+#             \
+# # build .deb files from upstream's source packages (which are verified by apt-get)
+#             && apt-get update \
+#             && apt-get build-dep -y $nginxPackages \
+#             && ( \
+#                 cd "$tempDir" \
+#                 && DEB_BUILD_OPTIONS="nocheck parallel=$(nproc)" \
+#                     apt-get source --compile $nginxPackages \
+#             ) \
+# # we don't remove APT lists here because they get re-downloaded and removed later
+#             \
+# # reset apt-mark's "manual" list so that "purge --auto-remove" will remove all build dependencies
+# # (which is done after we install the built packages so we don't have to redownload any overlapping dependencies)
+#             && apt-mark showmanual | xargs apt-mark auto > /dev/null \
+#             && { [ -z "$savedAptMark" ] || apt-mark manual $savedAptMark; } \
+#             \
+# # create a temporary local APT repo to install from (so that dependency resolution can be handled by APT, as it should be)
+#             && ls -lAFh "$tempDir" \
+#             && ( cd "$tempDir" && dpkg-scanpackages . > Packages ) \
+#             && grep '^Package: ' "$tempDir/Packages" \
+#             && echo "deb [ trusted=yes ] file://$tempDir ./" > /etc/apt/sources.list.d/temp.list \
+# # work around the following APT issue by using "Acquire::GzipIndexes=false" (overriding "/etc/apt/apt.conf.d/docker-gzip-indexes")
+# #   Could not open file /var/lib/apt/lists/partial/_tmp_tmp.ODWljpQfkE_._Packages - open (13: Permission denied)
+# #   ...
+# #   E: Failed to fetch store:/var/lib/apt/lists/partial/_tmp_tmp.ODWljpQfkE_._Packages  Could not open file /var/lib/apt/lists/partial/_tmp_tmp.ODWljpQfkE_._Packages - open (13: Permission denied)
+#             && apt-get -o Acquire::GzipIndexes=false update \
+#             ;; \
+#     esac \
+#     \
+    && apt-get install --no-install-recommends --no-install-suggests -y \
+#                         $nginxPackages \
+                        gettext-base \
+                        curl \
+    && apt-get remove --purge --auto-remove -y && rm -rf /var/lib/apt/lists/* /etc/apt/sources.list.d/nginx.list \
+    \
+# if we have leftovers from building, let's purge them (including extra, unnecessary build deps)
+#    && if [ -n "$tempDir" ]; then \
+#        apt-get purge -y --auto-remove \
+#        && rm -rf "$tempDir" /etc/apt/sources.list.d/temp.list; \
+#    fi \
+# forward request and error logs to docker log collector
+    && ln -sf /dev/stdout /var/log/nginx/access.log \
+    && ln -sf /dev/stderr /var/log/nginx/error.log \
+# create a docker-entrypoint.d directory
+    && mkdir /docker-entrypoint.d
+
 # Upgrade software to latest version
 # ##############################################################################
-    && apt-get upgrade -y \
+RUN apt-get upgrade -y \
 # Cleanup
 # ##############################################################################
     && apt-get autoremove -y \
diff --git a/tpl/Dockerfile.alpine-compat b/tpl/Dockerfile.alpine-compat
--- a/tpl/Dockerfile.alpine-compat
+++ b/tpl/Dockerfile.alpine-compat
@@ -155,6 +155,16 @@ ENV VER_OPENRESTY_STREAMLUA=$VER_OPENRESTY_STREAMLUA
 # https://github.com/nginx/nginx/releases
 ARG VER_NGINX={{VER_NGINX}}
 ENV VER_NGINX=$VER_NGINX
+
+# https://github.com/nginx/njs
+ARG VER_NJS={{VER_NJS}}
+ENV VER_NJS=$VER_NJS
+
+# Replicate same official env variable
+ENV NGINX_VERSION $VER_NGINX
+ENV NJS_VERSION   $VER_NJS
+ENV PKG_RELEASE   1
+
 # References:
 #  - https://developers.redhat.com/blog/2018/03/21/compiler-and-linker-flags-gcc
 #  - https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html
@@ -221,6 +231,7 @@ ARG NGINX_BUILD_CONFIG="\
             --with-stream_realip_module \
             --with-stream_ssl_module \
             --with-stream_ssl_preread_module \
+            --add-module=/njs-${VER_NJS}/nginx \
             --add-module=/lua-nginx-module-${VER_LUA_NGINX_MODULE} \
             --add-module=/ngx_devel_kit-${VER_NGX_DEVEL_KIT} \
             --add-module=/lua-upstream-nginx-module-${VER_LUA_UPSTREAM} \
@@ -259,11 +270,13 @@ ARG NGINX_BUILD_DEPS="\
         alpine-sdk \
         bash \
         findutils \
-        gd-dev \
-        libedit-dev \
-        libxslt-dev \
+        gcc \
+        libc-dev \
         linux-headers \
-        perl-dev \
+        make \
+        openssl-dev \
+        pcre2-dev \
+        zlib-dev \
 "
 ENV NGINX_BUILD_DEPS=$NGINX_BUILD_DEPS
 
@@ -365,12 +378,91 @@ RUN set -eux \
     && apk update \
     && apk add --no-cache --virtual .pkg_deps \
         $PKG_DEPS \
+    && mkdir -p /var/log/nginx \
+# Fix LUA alias
+    && ln -sf /usr/bin/lua${VER_LUA} /usr/local/bin/lua
+
+RUN set -x \
+# create nginx user/group first, to be consistent throughout docker variants
+    && addgroup -g 101 -S nginx \
+    && adduser -S -D -H -u 101 -h /var/cache/nginx -s /sbin/nologin -G nginx -g nginx nginx \
+# COMMENTED OUT FROM ORIGINAL DOCKERFILE: https://github.com/nginxinc/docker-nginx/blob/1.23.2/mainline/alpine-slim/Dockerfile
+# REASON: No need to use the existing distributed package as the binary is recompiled.
+#     && apkArch="$(cat /etc/apk/arch)" \
+#     && nginxPackages=" \
+#         nginx=${NGINX_VERSION}-r${PKG_RELEASE} \
+#     " \
+# # install prerequisites for public key and pkg-oss checks
+#     && apk add --no-cache --virtual .checksum-deps \
+#         openssl \
+#     && case "$apkArch" in \
+#         x86_64|aarch64) \
+# # arches officially built by upstream
+#             set -x \
+#             && KEY_SHA512="e09fa32f0a0eab2b879ccbbc4d0e4fb9751486eedda75e35fac65802cc9faa266425edf83e261137a2f4d16281ce2c1a5f4502930fe75154723da014214f0655" \
+#             && wget -O /tmp/nginx_signing.rsa.pub https://nginx.org/keys/nginx_signing.rsa.pub \
+#             && if echo "$KEY_SHA512 */tmp/nginx_signing.rsa.pub" | sha512sum -c -; then \
+#                 echo "key verification succeeded!"; \
+#                 mv /tmp/nginx_signing.rsa.pub /etc/apk/keys/; \
+#             else \
+#                 echo "key verification failed!"; \
+#                 exit 1; \
+#             fi \
+#             && apk add -X "https://nginx.org/packages/mainline/alpine/v$(egrep -o '^[0-9]+\.[0-9]+' /etc/alpine-release)/main" --no-cache $nginxPackages \
+#             ;; \
+#         *) \
+# # we're on an architecture upstream doesn't officially build for
+# # let's build binaries from the published packaging sources
+#             set -x \
+#             && tempDir="$(mktemp -d)" \
+#             && chown nobody:nobody $tempDir \
+#             && apk add --no-cache --virtual .build-deps \
+#                 gcc \
+#                 libc-dev \
+#                 make \
+#                 openssl-dev \
+#                 pcre2-dev \
+#                 zlib-dev \
+#                 linux-headers \
+#                 bash \
+#                 alpine-sdk \
+#                 findutils \
+#             && su nobody -s /bin/sh -c " \
+#                 export HOME=${tempDir} \
+#                 && cd ${tempDir} \
+#                 && curl -f -O https://hg.nginx.org/pkg-oss/archive/${NGINX_VERSION}-${PKG_RELEASE}.tar.gz \
+#                 && PKGOSSCHECKSUM=\"52a80f6c3b3914462f8a0b2fbadea950bcd79c1bd528386aff4c28d5a80c6920d783575a061a47b60fea800eef66bf5a0178a137ea51c37277fe9c2779715990 *${NGINX_VERSION}-${PKG_RELEASE}.tar.gz\" \
+#                 && if [ \"\$(openssl sha512 -r ${NGINX_VERSION}-${PKG_RELEASE}.tar.gz)\" = \"\$PKGOSSCHECKSUM\" ]; then \
+#                     echo \"pkg-oss tarball checksum verification succeeded!\"; \
+#                 else \
+#                     echo \"pkg-oss tarball checksum verification failed!\"; \
+#                     exit 1; \
+#                 fi \
+#                 && tar xzvf ${NGINX_VERSION}-${PKG_RELEASE}.tar.gz \
+#                 && cd pkg-oss-${NGINX_VERSION}-${PKG_RELEASE} \
+#                 && cd alpine \
+#                 && make base \
+#                 && apk index -o ${tempDir}/packages/alpine/${apkArch}/APKINDEX.tar.gz ${tempDir}/packages/alpine/${apkArch}/*.apk \
+#                 && abuild-sign -k ${tempDir}/.abuild/abuild-key.rsa ${tempDir}/packages/alpine/${apkArch}/APKINDEX.tar.gz \
+#                 " \
+#             && cp ${tempDir}/.abuild/abuild-key.rsa.pub /etc/apk/keys/ \
+#             && apk del .build-deps \
+#             && apk add -X ${tempDir}/packages/alpine/ add--no-cache $nginxPackages \
+#             ;; \
+#     esac \
+# # remove checksum deps
+#     && apk del .checksum-deps \
+# # if we have leftovers from building, let's purge them (including extra, unnecessary build deps)
+#     && if [ -n "$tempDir" ]; then rm -rf "$tempDir"; fi \
+#     && if [ -n "/etc/apk/keys/abuild-key.rsa.pub" ]; then rm -f /etc/apk/keys/abuild-key.rsa.pub; fi \
+#     && if [ -n "/etc/apk/keys/nginx_signing.rsa.pub" ]; then rm -f /etc/apk/keys/nginx_signing.rsa.pub; fi \
 # Bring in gettext so we can get `envsubst`, then throw
 # the rest away. To do this, we need to install `gettext`
 # then move `envsubst` out of the way so `gettext` can
 # be deleted completely, then move `envsubst` back.
     && apk add --no-cache --virtual .gettext gettext \
     && mv /usr/bin/envsubst /tmp/ \
+    \
     && runDeps="$( \
         scanelf --needed --nobanner /tmp/envsubst \
             | awk '{ gsub(/,/, "\nso:", $2); print "so:" $2 }' \
@@ -378,24 +470,21 @@ RUN set -eux \
             | xargs -r apk info --installed \
             | sort -u \
     )" \
-    && apk add --no-cache --virtual .run_deps $runDeps \
+    && apk add --no-cache $runDeps \
     && apk del .gettext \
     && mv /tmp/envsubst /usr/local/bin/ \
 # Bring in tzdata so users could set the timezones through the environment
 # variables
-    && apk add --no-cache --virtual pkg_tz tzdata \
-# Bring in curl and ca-certificates to make registering on DNS SD easier
-    && apk add --no-cache --virtual pkg_dns curl ca-certificates \
+    && apk add --no-cache tzdata \
 # forward request and error logs to docker log collector
-    && mkdir -p /var/log/nginx \
     && ln -sf /dev/stdout /var/log/nginx/access.log \
     && ln -sf /dev/stderr /var/log/nginx/error.log \
-# create nginx user/group first, to be consistent throughout docker variants
-    && addgroup -g 101 -S nginx \
-    && adduser -S -D -H -u 101 -h /var/cache/nginx -s /sbin/nologin -G nginx -g nginx nginx \
+# create a docker-entrypoint.d directory
+    && mkdir /docker-entrypoint.d
+
 # Upgrade software to latest version
 # ##############################################################################
-    && apk upgrade
+RUN apk upgrade
 
 # smoke test
 # ##############################################################################
