Automated updates

diff --git a/nginx/1.25.1/fedora/38/Dockerfile-compat b/nginx/1.25.1/fedora/38/Dockerfile-compat
--- a/nginx/1.25.1/fedora/38/Dockerfile-compat
+++ b/nginx/1.25.1/fedora/38/Dockerfile-compat
@@ -8,8 +8,8 @@
 # Repo: https://github.com/fabiocicerchia/nginx-lua
 
 ARG ARCH=
-ARG DISTRO=alpine
-ARG DISTRO_VER=3.18.2
+ARG DISTRO=fedora
+ARG DISTRO_VER=38
 
 #############################
 # Settings Common Variables #
@@ -60,8 +60,7 @@ ENV VER_GEOIP=$VER_GEOIP
 
 # lua
 # https://www.lua.org/versions.html
-# https://pkgs.alpinelinux.org/package/edge/main/x86/lua5.4
-ARG VER_LUA=5.4
+ARG VER_LUA=5.4.4
 ENV VER_LUA=$VER_LUA
 
 # luajit2
@@ -73,6 +72,7 @@ ARG LUAJIT_LIB=/usr/local/lib
 ENV LUAJIT_LIB=$LUAJIT_LIB
 ARG LUAJIT_INC=/usr/local/include/luajit-2.1
 ENV LUAJIT_INC=$LUAJIT_INC
+ENV LUA_INCDIR=$LUAJIT_INC
 ARG LD_LIBRARY_PATH=/usr/local/lib/:$LD_LIBRARY_PATH
 ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH
 
@@ -200,7 +200,8 @@ ENV PKG_RELEASE     1~$DISTRO_VER
 # -Wp,-D_FORTIFY_SOURCE=2   Run-time buffer overflow detection
 # -fPIC                     No text relocations
 # ORIGINAL VALUE: -g -O2 -ffile-prefix-map=/data/builder/debuild/nginx-1.23.3/debian/debuild-base/nginx-1.23.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fPIC
-ARG NGX_CFLAGS="-g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fPIC"
+# Ref: https://www.mail-archive.com/nginx-devel@nginx.org/msg13233.html
+ARG NGX_CFLAGS="-g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fPIC -Wno-dangling-pointer"
 ENV NGX_CFLAGS=$NGX_CFLAGS
 # References
 #  - https://developers.redhat.com/blog/2018/03/21/compiler-and-linker-flags-gcc
@@ -271,46 +272,34 @@ ARG NGINX_BUILD_CONFIG="\
 ENV NGINX_BUILD_CONFIG=$NGINX_BUILD_CONFIG
 
 ARG BUILD_DEPS_BASE="\
-        curl \
+        ca-certificates \
+        # findutils \
+        gcc-c++ \
         gzip \
-        libmaxminddb-dev \
-        lua${VER_LUA} \
-        lua${VER_LUA}-dev \
+        libmaxminddb-devel \
+        libxml2-devel \
+        libxslt-devel \
         make \
-        openssl-dev \
+        openssl-devel \
         patch \
-        pcre-dev \
+        pcre-devel \
         tar \
-        zlib-dev \
+        unzip \
+        which \
+        zlib-devel \
 "
 ENV BUILD_DEPS_BASE=$BUILD_DEPS_BASE
 ARG BUILD_DEPS_AMD64="\
         ${BUILD_DEPS_BASE} \
-        g++ \
 "
 ENV BUILD_DEPS_AMD64=$BUILD_DEPS_AMD64
 ARG BUILD_DEPS_ARM64V8="\
         ${BUILD_DEPS_BASE} \
-        gcc-aarch64-none-elf \
 "
 ENV BUILD_DEPS_ARM64V8=$BUILD_DEPS_ARM64V8
 ENV BUILD_DEPS=
 
-ARG NGINX_BUILD_DEPS="\
-# NGINX
-        alpine-sdk \
-        bash \
-        findutils \
-        gcc \
-        libc-dev \
-        libxml2-dev \
-        libxslt-dev \
-        linux-headers \
-        make \
-        openssl-dev \
-        pcre-dev \
-        zlib-dev \
-"
+ARG NGINX_BUILD_DEPS=""
 ENV NGINX_BUILD_DEPS=$NGINX_BUILD_DEPS
 
 ####################################
@@ -321,16 +310,23 @@ FROM base AS builder
 # hadolint ignore=SC2086
 RUN set -eux \
     && eval BUILD_DEPS="\$$(echo BUILD_DEPS_${ARCH} | tr '[:lower:]' '[:upper:]')" \
-    && apk update \
-    && apk add --no-cache \
+    && rpm --import https://src.fedoraproject.org/rpms/fedora-repos/raw/rawhide/f/RPM-GPG-KEY-fedora-$(. /etc/os-release; echo $VERSION_ID)-primary \
+    && yum install -y \
         $BUILD_DEPS \
         $NGINX_BUILD_DEPS
 
 COPY tpl/Makefile Makefile
 
 RUN make deps \
+    && make lua-src \
     && make core \
     && make luarocks
+
+RUN set -eux \
+# envsubst
+# ##############################################################################
+    && yum install -y \
+        gettext
 
 ##########################################
 # Combine everything with minimal layers #
@@ -340,18 +336,18 @@ FROM base
 # http://label-schema.org/rc1/
 LABEL maintainer="Fabio Cicerchia <info@fabiocicerchia.it>" \
     org.label-schema.build-date="${BUILD_DATE}" \
-    org.label-schema.description="Nginx ${VER_NGINX} with Lua support based on alpine (${ARCH}) 3.18.2." \
-    org.label-schema.docker.cmd="docker run -p 80:80 -d ${DOCKER_IMAGE}:${VER_NGINX}-alpine3.18.2" \
+    org.label-schema.description="Nginx ${VER_NGINX} with Lua support based on fedora (${ARCH}) 38." \
+    org.label-schema.docker.cmd="docker run -p 80:80 -d ${DOCKER_IMAGE}:${VER_NGINX}-fedora38" \
     org.label-schema.name="${DOCKER_IMAGE}" \
     org.label-schema.schema-version="1.0" \
     org.label-schema.url="https://github.com/${DOCKER_IMAGE}" \
     org.label-schema.vcs-ref=$VCS_REF \
     org.label-schema.vcs-url="https://github.com/${DOCKER_IMAGE}" \
-    org.label-schema.version="${VER_NGINX}-alpine3.18.2" \
+    org.label-schema.version="${VER_NGINX}-fedora38" \
     image.target.platform="${TARGETPLATFORM}" \
     image.target.os="${TARGETOS}" \
     image.target.arch="${ARCH}" \
-    versions.os="3.18.2" \
+    versions.os="38" \
     versions.lua="${VER_LUA}" \
     versions.luajit2="${VER_LUAJIT}" \
     versions.luarocks="${VER_LUAROCKS}" \
@@ -378,22 +374,22 @@ LABEL maintainer="Fabio Cicerchia <info@fabiocicerchia.it>" \
     versions.set-misc-nginx=${VER_MISC_NGINX} \
     versions.stream-lua-nginx-module="${VER_OPENRESTY_STREAMLUA}"
 
-# wget is required due to https://github.com/luarocks/luarocks/issues/952
 ARG PKG_DEPS="\
-        curl \
-        libmaxminddb-dev \
-        libxml2-dev \
-        lua${VER_LUA} \
-        lua${VER_LUA}-dev \
-        openssl-dev \
-        pcre-dev \
+        ca-certificates \
+        gcc-c++ \
+        libxml2-devel \
+        openssl-devel \
+        pcre-devel \
         unzip \
-        wget \
-        zlib-dev \
+        zlib-devel \
 "
 ENV PKG_DEPS=$PKG_DEPS
 
 COPY --from=builder --chown=101:101 /etc/nginx /etc/nginx
+COPY --from=builder --chown=101:101 /usr/bin/envsubst /usr/local/bin/envsubst
+COPY --from=builder --chown=101:101 /usr/lib64 /usr/lib64
+COPY --from=builder --chown=101:101 /usr/local/bin/lua /usr/local/bin/lua
+COPY --from=builder --chown=101:101 /usr/local/bin/luajit /usr/local/bin/luajit
 COPY --from=builder --chown=101:101 /usr/local/bin/luarocks /usr/local/bin/luarocks
 COPY --from=builder --chown=101:101 /usr/local/etc/luarocks /usr/local/etc/luarocks
 COPY --from=builder --chown=101:101 /usr/local/lib /usr/local/lib
@@ -401,6 +397,7 @@ COPY --from=builder --chown=101:101 /usr/local/share/lua /usr/local/share/lua
 COPY --from=builder --chown=101:101 /usr/sbin/nginx /usr/sbin/nginx
 COPY --from=builder --chown=101:101 /usr/sbin/nginx-debug /usr/sbin/nginx-debug
 COPY --from=builder --chown=101:101 /var/cache/nginx /var/cache/nginx
+COPY --from=builder --chown=101:101 $LUAJIT_INC $LUAJIT_INC
 
 COPY --chown=101:101 tpl/??-*.sh /docker-entrypoint.d/
 COPY --chown=101:101 tpl/default.conf /etc/nginx/conf.d/default.conf
@@ -408,122 +405,31 @@ COPY --chown=101:101 tpl/docker-entrypoint.sh /
 COPY --chown=101:101 tpl/nginx.conf /etc/nginx/nginx.conf
 COPY --chown=101:101 tpl/support.sh /
 
-SHELL ["/bin/ash", "-eo", "pipefail", "-c"]
+SHELL ["/bin/sh", "-o", "pipefail", "-c"]
 
 # hadolint ignore=SC2086
 RUN set -eux \
-    && apk update \
-    && apk add --no-cache --virtual .pkg_deps \
+    && yum install -y \
         $PKG_DEPS \
-    && mkdir -p /var/log/nginx \
-# Fix LUA alias
-    && ln -sf /usr/bin/lua${VER_LUA} /usr/local/bin/lua
-
-RUN set -x \
-# create nginx user/group first, to be consistent throughout docker variants
-    && addgroup -g 101 -S nginx \
-    && adduser -S -D -H -u 101 -h /var/cache/nginx -s /sbin/nologin -G nginx -g nginx nginx \
-# COMMENTED OUT FROM ORIGINAL DOCKERFILE: https://github.com/nginxinc/docker-nginx/blob/1.23.2/mainline/alpine/Dockerfile
-# REASON: No need to use the existing distributed package as the binary is recompiled.
-#     && apkArch="$(cat /etc/apk/arch)" \
-#     && nginxPackages=" \
-#         nginx=${NGINX_VERSION}-r${PKG_RELEASE} \
-#         nginx-module-xslt=${NGINX_VERSION}-r${PKG_RELEASE} \
-#         nginx-module-geoip=${NGINX_VERSION}-r${PKG_RELEASE} \
-#         nginx-module-image-filter=${NGINX_VERSION}-r${PKG_RELEASE} \
-#         nginx-module-njs=${NGINX_VERSION}.${NJS_VERSION}-r${PKG_RELEASE} \
-#     " \
-# # install prerequisites for public key and pkg-oss checks
-#     && apk add --no-cache --virtual .checksum-deps \
-#         openssl \
-#     && case "$apkArch" in \
-#         x86_64|aarch64) \
-# # arches officially built by upstream
-#             set -x \
-#             && KEY_SHA512="e09fa32f0a0eab2b879ccbbc4d0e4fb9751486eedda75e35fac65802cc9faa266425edf83e261137a2f4d16281ce2c1a5f4502930fe75154723da014214f0655" \
-#             && wget -O /tmp/nginx_signing.rsa.pub https://nginx.org/keys/nginx_signing.rsa.pub \
-#             && if echo "$KEY_SHA512 */tmp/nginx_signing.rsa.pub" | sha512sum -c -; then \
-#                 echo "key verification succeeded!"; \
-#                 mv /tmp/nginx_signing.rsa.pub /etc/apk/keys/; \
-#             else \
-#                 echo "key verification failed!"; \
-#                 exit 1; \
-#             fi \
-#             && apk add -X "https://nginx.org/packages/mainline/alpine/v$(egrep -o '^[0-9]+\.[0-9]+' /etc/alpine-release)/main" --no-cache $nginxPackages \
-#             ;; \
-#         *) \
-# # we're on an architecture upstream doesn't officially build for
-# # let's build binaries from the published packaging sources
-#             set -x \
-#             && tempDir="$(mktemp -d)" \
-#             && chown nobody:nobody $tempDir \
-#             && apk add --no-cache --virtual .build-deps \
-#                 gcc \
-#                 libc-dev \
-#                 make \
-#                 openssl-dev \
-#                 pcre2-dev \
-#                 zlib-dev \
-#                 linux-headers \
-#                 bash \
-#                 alpine-sdk \
-#                 findutils \
-#             && su nobody -s /bin/sh -c " \
-#                 export HOME=${tempDir} \
-#                 && cd ${tempDir} \
-#                 && curl -f -O https://hg.nginx.org/pkg-oss/archive/${NGINX_VERSION}-${PKG_RELEASE}.tar.gz \
-#                 && PKGOSSCHECKSUM=\"52a80f6c3b3914462f8a0b2fbadea950bcd79c1bd528386aff4c28d5a80c6920d783575a061a47b60fea800eef66bf5a0178a137ea51c37277fe9c2779715990 *${NGINX_VERSION}-${PKG_RELEASE}.tar.gz\" \
-#                 && if [ \"\$(openssl sha512 -r ${NGINX_VERSION}-${PKG_RELEASE}.tar.gz)\" = \"\$PKGOSSCHECKSUM\" ]; then \
-#                     echo \"pkg-oss tarball checksum verification succeeded!\"; \
-#                 else \
-#                     echo \"pkg-oss tarball checksum verification failed!\"; \
-#                     exit 1; \
-#                 fi \
-#                 && tar xzvf ${NGINX_VERSION}-${PKG_RELEASE}.tar.gz \
-#                 && cd pkg-oss-${NGINX_VERSION}-${PKG_RELEASE} \
-#                 && cd alpine \
-#                 && make base \
-#                 && apk index -o ${tempDir}/packages/alpine/${apkArch}/APKINDEX.tar.gz ${tempDir}/packages/alpine/${apkArch}/*.apk \
-#                 && abuild-sign -k ${tempDir}/.abuild/abuild-key.rsa ${tempDir}/packages/alpine/${apkArch}/APKINDEX.tar.gz \
-#                 " \
-#             && cp ${tempDir}/.abuild/abuild-key.rsa.pub /etc/apk/keys/ \
-#             && apk del .build-deps \
-#             && apk add -X ${tempDir}/packages/alpine/ add--no-cache $nginxPackages \
-#             ;; \
-#     esac \
-# # remove checksum deps
-#     && apk del .checksum-deps \
-# # if we have leftovers from building, let's purge them (including extra, unnecessary build deps)
-#     && if [ -n "$tempDir" ]; then rm -rf "$tempDir"; fi \
-#     && if [ -n "/etc/apk/keys/abuild-key.rsa.pub" ]; then rm -f /etc/apk/keys/abuild-key.rsa.pub; fi \
-#     && if [ -n "/etc/apk/keys/nginx_signing.rsa.pub" ]; then rm -f /etc/apk/keys/nginx_signing.rsa.pub; fi \
-# Bring in gettext so we can get `envsubst`, then throw
-# the rest away. To do this, we need to install `gettext`
-# then move `envsubst` out of the way so `gettext` can
-# be deleted completely, then move `envsubst` back.
-    && apk add --no-cache --virtual .gettext gettext \
-    && mv /usr/bin/envsubst /tmp/ \
-    \
-    && runDeps="$( \
-        scanelf --needed --nobanner /tmp/envsubst \
-            | awk '{ gsub(/,/, "\nso:", $2); print "so:" $2 }' \
-            | sort -u \
-            | xargs -r apk info --installed \
-            | sort -u \
-    )" \
-    && apk add --no-cache $runDeps \
-    && apk del .gettext \
-    && mv /tmp/envsubst /usr/local/bin/ \
 # Bring in tzdata so users could set the timezones through the environment
 # variables
-    && apk add --no-cache tzdata \
+    && yum install -y tzdata \
+# Bring in curl and ca-certificates to make registering on DNS SD easier
+    && yum install -y curl ca-certificates \
 # forward request and error logs to docker log collector
+    && mkdir -p /var/log/nginx \
     && ln -sf /dev/stdout /var/log/nginx/access.log \
-    && ln -sf /dev/stderr /var/log/nginx/error.log
-
+    && ln -sf /dev/stderr /var/log/nginx/error.log \
+# create nginx user/group first, to be consistent throughout docker variants
+    && groupadd --system --gid 101 nginx \
+    && useradd --system --gid nginx --no-create-home --home /nonexistent --comment "nginx user" --shell /bin/false --uid 101 nginx \
 # Upgrade software to latest version
 # ##############################################################################
-RUN apk upgrade
+    && yum upgrade -y \
+# Cleanup
+# ##############################################################################
+    && yum clean all \
+    && rm -rf /var/cache/dnf
 
 # smoke test
 # ##############################################################################
