Automated updates

diff --git a/nginx/1.21.5/debian/11.2/Dockerfile-compat b/nginx/1.21.5/debian/11.2/Dockerfile-compat
--- a/nginx/1.21.5/debian/11.2/Dockerfile-compat
+++ b/nginx/1.21.5/debian/11.2/Dockerfile-compat
@@ -10,13 +10,13 @@
 #############################
 # Settings Common Variables #
 #############################
-FROM alpine:3.15.0 AS base
+FROM debian:11.2 AS base
 
 ARG DOCKER_IMAGE=fabiocicerchia/nginx-lua
 ENV DOCKER_IMAGE=$DOCKER_IMAGE
-ARG DOCKER_IMAGE_OS=alpine
+ARG DOCKER_IMAGE_OS=debian
 ENV DOCKER_IMAGE_OS=$DOCKER_IMAGE_OS
-ARG DOCKER_IMAGE_TAG=3.15.0
+ARG DOCKER_IMAGE_TAG=11.2
 ENV DOCKER_IMAGE_TAG=$DOCKER_IMAGE_TAG
 
 ARG BUILD_DATE
@@ -28,7 +28,7 @@ ARG EXTENDED_IMAGE=1
 ENV EXTENDED_IMAGE=$EXTENDED_IMAGE
 
 # lua
-ARG VER_LUA=5.4
+ARG VER_LUA=5.4.3
 ENV VER_LUA=$VER_LUA
 
 # ngx_devel_kit
@@ -45,6 +45,7 @@ ARG LUAJIT_LIB=/usr/local/lib
 ENV LUAJIT_LIB=$LUAJIT_LIB
 ARG LUAJIT_INC=/usr/local/include/luajit-2.1
 ENV LUAJIT_INC=$LUAJIT_INC
+ENV LUA_INCDIR=$LUAJIT_INC
 ARG LD_LIBRARY_PATH=/usr/local/lib/:$LD_LIBRARY_PATH
 ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH
 
@@ -198,40 +199,23 @@ ARG NGINX_BUILD_CONFIG="\
 ENV NGINX_BUILD_CONFIG=$NGINX_BUILD_CONFIG
 
 ARG BUILD_DEPS="\
+        ca-certificates \
         curl \
         g++ \
-        geoip-dev \
-        gzip \
-        lua${VER_LUA} \
-        lua${VER_LUA}-dev \
+        libgeoip-dev \
+        libpcre3-dev \
+        libssl-dev \
         make \
-        openssl-dev \
         patch \
-        pcre-dev \
-        tar \
-        zlib-dev \
+        unzip \
+        zlib1g-dev \
 "
 ENV BUILD_DEPS=$BUILD_DEPS
 
-ARG NGINX_BUILD_DEPS="\
-# NGINX
-        alpine-sdk \
-        bash \
-        findutils \
-        gcc \
-        gd-dev \
-        geoip-dev \
-        libc-dev \
-        libedit-dev \
-        libxslt-dev \
-        linux-headers \
-        make \
-        openssl-dev \
-        pcre-dev \
-        perl-dev \
-        zlib-dev \
-"
+ARG NGINX_BUILD_DEPS=""
 ENV NGINX_BUILD_DEPS=$NGINX_BUILD_DEPS
+
+ENV DEBIAN_FRONTEND noninteractive
 
 ####################################
 # Build Nginx with support for LUA #
@@ -243,8 +227,10 @@ COPY tpl/Makefile Makefile
 # TODO: NGINX_BUILD_CONFIG not updated
 # hadolint ignore=SC2086
 RUN set -eux \
-    && apk update \
-    && apk add --no-cache \
+    && apt-get update \
+    && apt-get install -y --no-install-recommends --no-install-suggests \
+        apt-utils \
+    && apt-get install -y --no-install-recommends --no-install-suggests \
         $BUILD_DEPS \
         $NGINX_BUILD_DEPS \
     && [ $EXTENDED_IMAGE -eq 1 ] && \
@@ -252,9 +238,19 @@ RUN set -eux \
             --add-module=/headers-more-nginx-module-${VER_OPENRESTY_HEADERS} \
             --add-module=/stream-lua-nginx-module-${VER_OPENRESTY_STREAMLUA} \
         " \
+    && make -j "$(nproc)" lua-src \
     && make -j "$(nproc)" deps \
     && make -j "$(nproc)" core \
-    && make luarocks
+    && make luarocks \
+    && rm -rf /var/lib/apt/lists/*
+
+RUN set -eux \
+# envsubst
+# ##############################################################################
+    && apt-get update \
+    && apt-get install -y --no-install-recommends --no-install-suggests \
+        gettext-base \
+    && rm -rf /var/lib/apt/lists/*
 
 ##########################################
 # Combine everything with minimal layers #
@@ -298,13 +294,12 @@ LABEL maintainer="Fabio Cicerchia <info@fabiocicerchia.it>" \
     versions.stream-lua-nginx-module=${VER_OPENRESTY_STREAMLUA}
 
 ARG PKG_DEPS="\
-        geoip-dev \
-        lua${VER_LUA} \
-        lua${VER_LUA}-dev \
-        openssl-dev \
-        pcre-dev \
+        ca-certificates \
+        libgeoip-dev \
+        libpcre3-dev \
+        libssl-dev \
         unzip \
-        zlib-dev \
+        zlib1g-dev \
 "
 ENV PKG_DEPS=$PKG_DEPS
 
@@ -314,47 +309,37 @@ COPY --from=builder /usr/local/share/lua /usr/local/share/lua
 COPY --from=builder /usr/sbin/nginx /usr/sbin/nginx
 COPY --from=builder /usr/sbin/nginx-debug /usr/sbin/nginx-debug
 COPY --from=builder /var/cache/nginx /var/cache/nginx
+COPY --from=builder /usr/bin/envsubst /usr/local/bin/envsubst
+COPY --from=builder /usr/local/bin/lua /usr/local/bin/lua
+COPY --from=builder /usr/local/bin/luajit /usr/local/bin/luajit
 COPY --from=builder /usr/local/bin/luarocks /usr/local/bin/luarocks
 COPY --from=builder /usr/local/etc/luarocks /usr/local/etc/luarocks
+COPY --from=builder $LUAJIT_INC $LUAJIT_INC
 
-SHELL ["/bin/ash", "-eo", "pipefail", "-c"]
+SHELL ["/bin/bash", "-o", "pipefail", "-c"]
 
 # hadolint ignore=SC2086
 RUN set -eux \
-    && apk update \
-    && apk add --no-cache --virtual .pkg_deps \
+    && apt-get update \
+    && apt-get install -y --no-install-recommends --no-install-suggests \
         $PKG_DEPS \
-# Fix LUA alias
-    && ln -sf /usr/bin/lua${VER_LUA} /usr/local/bin/lua \
-# Bring in gettext so we can get `envsubst`, then throw
-# the rest away. To do this, we need to install `gettext`
-# then move `envsubst` out of the way so `gettext` can
-# be deleted completely, then move `envsubst` back.
-    && apk add --no-cache --virtual .gettext gettext \
-    && mv /usr/bin/envsubst /tmp/ \
-    && runDeps="$( \
-        scanelf --needed --nobanner /tmp/envsubst \
-            | awk '{ gsub(/,/, "\nso:", $2); print "so:" $2 }' \
-            | sort -u \
-            | xargs -r apk info --installed \
-            | sort -u \
-    )" \
-    && apk add --no-cache --virtual .run_deps $runDeps \
-    && apk del .gettext \
-    && mv /tmp/envsubst /usr/local/bin/ \
 # Bring in tzdata so users could set the timezones through the environment
 # variables
-    && apk add --no-cache --virtual pkg_tz tzdata \
+    && apt-get install -y --no-install-recommends --no-install-suggests tzdata \
 # Bring in curl and ca-certificates to make registering on DNS SD easier
-    && apk add --no-cache --virtual pkg_dns curl ca-certificates \
+    && apt-get install -y --no-install-recommends --no-install-suggests curl ca-certificates \
 # forward request and error logs to docker log collector
     && mkdir -p /var/log/nginx \
     && ln -sf /dev/stdout /var/log/nginx/access.log \
     && ln -sf /dev/stderr /var/log/nginx/error.log \
 # create nginx user/group first, to be consistent throughout docker variants
-    && addgroup -g 101 -S nginx \
-    && adduser -S -D -H -u 101 -h /var/cache/nginx -s /sbin/nologin -G nginx -g nginx nginx \
-    && mkdir /docker-entrypoint.d
+    && addgroup --system --gid 101 nginx \
+    && adduser --system --disabled-login --ingroup nginx --no-create-home --home /nonexistent --gecos "nginx user" --shell /bin/false --uid 101 nginx \
+    && mkdir /docker-entrypoint.d \
+# Cleanup
+# ##############################################################################
+    && apt-get autoremove -y \
+    && rm -rf /var/lib/apt/lists/*
 
 COPY tpl/support.sh /
 COPY tpl/docker-entrypoint.sh /
