Automated updates

diff --git a/nginx/1.29.0/ubuntu/24.04/Dockerfile b/nginx/1.29.0/ubuntu/24.04/Dockerfile
--- a/nginx/1.29.0/ubuntu/24.04/Dockerfile
+++ b/nginx/1.29.0/ubuntu/24.04/Dockerfile
@@ -8,8 +8,8 @@
 # Repo: https://github.com/fabiocicerchia/nginx-lua
 
 ARG ARCH=
-ARG DISTRO=alpine
-ARG DISTRO_VER=3.22.0
+ARG DISTRO=ubuntu
+ARG DISTRO_VER=24.04
 
 #############################
 # Settings Common Variables #
@@ -221,10 +221,11 @@ ENV PKG_RELEASE     1~$DISTRO_VER
 # -fstack-protector-strong  Stack smashing protector
 # -Wformat                  Check calls to make sure that the arguments supplied have types appropriate to the format string specified
 # -Werror=format-security   Reject potentially unsafe format string arguents
+# -U_FORTIFY_SOURCE         Unset _FORTIFY_SOURCE before defining it (turns out that some gcc builds, depends on the distro, set _FORTIFY_SOURCE internally)
 # -Wp,-D_FORTIFY_SOURCE=2   Run-time buffer overflow detection
 # -fPIC                     No text relocations
 # ORIGINAL VALUE: -g -O2 -ffile-prefix-map=/home/builder/debuild/nginx-1.27.5/debian/debuild-base/nginx-1.27.5=. -fstack-protector-strong -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fPIC
-ARG NGX_CFLAGS="-g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fPIC"
+ARG NGX_CFLAGS="-g -O2 -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -Wp,-D_FORTIFY_SOURCE=2 -fPIC"
 ENV NGX_CFLAGS=$NGX_CFLAGS
 # References
 #  - https://developers.redhat.com/blog/2018/03/21/compiler-and-linker-flags-gcc
@@ -296,47 +297,37 @@ ARG NGINX_BUILD_CONFIG="\
 ENV NGINX_BUILD_CONFIG=$NGINX_BUILD_CONFIG
 
 ARG BUILD_DEPS_BASE="\
+        ca-certificates \
         curl \
-        gzip \
+        g++ \
         libmaxminddb-dev \
+        libpcre3-dev \
+        libssl-dev \
+        libxml2-dev \
+        libxslt1-dev \
         make \
-        openssl-dev \
         patch \
-        pcre-dev \
-        tar \
-        zlib-dev \
+        unzip \
+        zlib1g-dev \
 "
 ENV BUILD_DEPS_BASE=$BUILD_DEPS_BASE
 ARG BUILD_DEPS_AMD64="\
         ${BUILD_DEPS_BASE} \
-        g++ \
 "
 ENV BUILD_DEPS_AMD64=$BUILD_DEPS_AMD64
 ARG BUILD_DEPS_ARM64V8="\
         ${BUILD_DEPS_BASE} \
-        gcc-aarch64-none-elf \
 "
 ENV BUILD_DEPS_ARM64V8=$BUILD_DEPS_ARM64V8
 ENV BUILD_DEPS=
 
 ARG NGINX_BUILD_DEPS="\
-# NGINX
-        alpine-sdk \
-        bash \
-        findutils \
-        gcc \
-        libc-dev \
-        libxml2-dev \
-        libxslt-dev \
-        linux-headers \
-        make \
-        openssl-dev \
-        pcre-dev \
-        zlib-dev \
 # OPENRESTY PATCHES
         git \
 "
 ENV NGINX_BUILD_DEPS=$NGINX_BUILD_DEPS
+
+ENV DEBIAN_FRONTEND noninteractive
 
 ####################################
 # Build Nginx with support for LUA #
@@ -346,10 +337,13 @@ FROM base AS builder
 # hadolint ignore=SC2086
 RUN set -eux \
     && eval BUILD_DEPS="\$$(echo BUILD_DEPS_${ARCH} | tr '[:lower:]' '[:upper:]')" \
-    && apk update \
-    && apk add --no-cache \
+    && apt-get update \
+    && apt-get install -y --no-install-recommends --no-install-suggests \
+        apt-utils \
+    && apt-get install -y --no-install-recommends --no-install-suggests \
         $BUILD_DEPS \
-        $NGINX_BUILD_DEPS
+        $NGINX_BUILD_DEPS \
+    && rm -rf /var/lib/apt/lists/*
 
 COPY tpl/Makefile Makefile
 COPY tpl/patches patches
@@ -366,18 +360,18 @@ FROM base
 # http://label-schema.org/rc1/
 LABEL maintainer="Fabio Cicerchia <info@fabiocicerchia.it>" \
     org.label-schema.build-date="${BUILD_DATE}" \
-    org.label-schema.description="Nginx ${VER_NGINX} with Lua support based on alpine (${ARCH}) 3.22.0." \
-    org.label-schema.docker.cmd="docker run -p 80:80 -d ${DOCKER_IMAGE}:${VER_NGINX}-alpine3.22.0" \
+    org.label-schema.description="Nginx ${VER_NGINX} with Lua support based on ubuntu (${ARCH}) 24.04." \
+    org.label-schema.docker.cmd="docker run -p 80:80 -d ${DOCKER_IMAGE}:${VER_NGINX}-ubuntu24.04" \
     org.label-schema.name="${DOCKER_IMAGE}" \
     org.label-schema.schema-version="1.0" \
     org.label-schema.url="https://github.com/${DOCKER_IMAGE}" \
     org.label-schema.vcs-ref=$VCS_REF \
     org.label-schema.vcs-url="https://github.com/${DOCKER_IMAGE}" \
-    org.label-schema.version="${VER_NGINX}-alpine3.22.0" \
+    org.label-schema.version="${VER_NGINX}-ubuntu24.04" \
     image.target.platform="${TARGETPLATFORM}" \
     image.target.os="${TARGETOS}" \
     image.target.arch="${ARCH}" \
-    versions.os="3.22.0" \
+    versions.os="24.04" \
     versions.luajit2="${VER_LUAJIT}" \
     versions.luarocks="${VER_LUAROCKS}" \
     versions.nginx="${VER_NGINX}" \
@@ -408,20 +402,19 @@ LABEL maintainer="Fabio Cicerchia <info@fabiocicerchia.it>" \
     versions.set-misc-nginx=${VER_MISC_NGINX} \
     versions.stream-lua-nginx-module="${VER_OPENRESTY_STREAMLUA}"
 
-# wget is required due to https://github.com/luarocks/luarocks/issues/952
 ARG PKG_DEPS="\
-        curl \
+        ca-certificates \
         libmaxminddb-dev \
+        libpcre3-dev \
+        libssl-dev \
         libxml2-dev \
-        openssl-dev \
-        pcre-dev \
         unzip \
-        wget \
-        zlib-dev \
+        zlib1g-dev \
 "
 ENV PKG_DEPS=$PKG_DEPS
 
 COPY --from=builder --chown=101:101 /etc/nginx /etc/nginx
+COPY --from=builder --chown=101:101 /usr/lib64 /usr/lib64
 COPY --from=builder --chown=101:101 /usr/local/lib /usr/local/lib
 COPY --from=builder --chown=101:101 /usr/local/share/lua /usr/local/share/lua
 COPY --from=builder --chown=101:101 /usr/sbin/nginx /usr/sbin/nginx
@@ -445,128 +438,123 @@ COPY --chown=101:101 tpl/docker-entrypoint.sh /
 COPY --chown=101:101 tpl/nginx.conf /etc/nginx/nginx.conf
 COPY --chown=101:101 tpl/support.sh /
 
-SHELL ["/bin/ash", "-eo", "pipefail", "-c"]
+SHELL ["/bin/bash", "-o", "pipefail", "-c"]
+
+ENV DEBIAN_FRONTEND noninteractive
 
 # hadolint ignore=SC2086
 RUN set -eux \
-    && apk update \
-    && apk add --no-cache --virtual .pkg_deps \
+    && apt-get update \
+    && apt-get install -y --no-install-recommends --no-install-suggests \
         $PKG_DEPS \
+    && rm -rf /var/lib/apt/lists/* \
     && mkdir -p /var/log/nginx \
 # Fix LUA alias
     && ln -sf /usr/local/bin/luajit /usr/local/bin/lua
 
 RUN set -x \
 # create nginx user/group first, to be consistent throughout docker variants
-    && addgroup -g 101 -S nginx \
-    && adduser -S -D -H -u 101 -h /var/cache/nginx -s /sbin/nologin -G nginx -g nginx nginx \
-# COMMENTED OUT FROM ORIGINAL DOCKERFILE: https://github.com/nginxinc/docker-nginx/blob/1.25.4/mainline/alpine/Dockerfile
+    && groupadd --system --gid 101 nginx \
+    && useradd --system --gid nginx --no-create-home --home /nonexistent --comment "nginx user" --shell /bin/false --uid 101 nginx \
+    && apt-get update \
+    && apt-get install --no-install-recommends --no-install-suggests -y gnupg1 ca-certificates \
+# COMMENTED OUT FROM ORIGINAL DOCKERFILE: https://github.com/nginxinc/docker-nginx/blob/1.25.4/mainline/debian/Dockerfile
 # REASON: No need to use the existing distributed package as the binary is recompiled.
-#     && apkArch="$(cat /etc/apk/arch)" \
+#     && \
+#     NGINX_GPGKEY=573BFD6B3D8FBC641079A6ABABF5BD827BD9BF62; \
+#     NGINX_GPGKEY_PATH=/usr/share/keyrings/nginx-archive-keyring.gpg; \
+#     export GNUPGHOME="$(mktemp -d)"; \
+#     found=''; \
+#     for server in \
+#         hkp://keyserver.ubuntu.com:80 \
+#         pgp.mit.edu \
+#     ; do \
+#         echo "Fetching GPG key $NGINX_GPGKEY from $server"; \
+#         gpg1 --keyserver "$server" --keyserver-options timeout=10 --recv-keys "$NGINX_GPGKEY" && found=yes && break; \
+#     done; \
+#     test -z "$found" && echo >&2 "error: failed to fetch GPG key $NGINX_GPGKEY" && exit 1; \
+#     gpg1 --export "$NGINX_GPGKEY" > "$NGINX_GPGKEY_PATH" ; \
+#     rm -rf "$GNUPGHOME"; \
+#     apt-get remove --purge --auto-remove -y gnupg1 && rm -rf /var/lib/apt/lists/* \
+#     && dpkgArch="$(dpkg --print-architecture)" \
 #     && nginxPackages=" \
-#         nginx=${NGINX_VERSION}-r${PKG_RELEASE} \
-#         nginx-module-xslt=${NGINX_VERSION}-r${PKG_RELEASE} \
-#         nginx-module-geoip=${NGINX_VERSION}-r${PKG_RELEASE} \
-#         nginx-module-image-filter=${NGINX_VERSION}-r${PKG_RELEASE} \
-#         nginx-module-njs=${NGINX_VERSION}.${NJS_VERSION}-r${PKG_RELEASE} \
+#         nginx=${NGINX_VERSION}-${PKG_RELEASE} \
+#         nginx-module-xslt=${NGINX_VERSION}-${PKG_RELEASE} \
+#         nginx-module-geoip=${NGINX_VERSION}-${PKG_RELEASE} \
+#         nginx-module-image-filter=${NGINX_VERSION}-${PKG_RELEASE} \
+#         nginx-module-njs=${NGINX_VERSION}+${NJS_VERSION}-${PKG_RELEASE} \
 #     " \
-# # install prerequisites for public key and pkg-oss checks
-#     && apk add --no-cache --virtual .checksum-deps \
-#         openssl \
-#     && case "$apkArch" in \
-#         x86_64|aarch64) \
-# # arches officially built by upstream
-#             set -x \
-#             && KEY_SHA512="e09fa32f0a0eab2b879ccbbc4d0e4fb9751486eedda75e35fac65802cc9faa266425edf83e261137a2f4d16281ce2c1a5f4502930fe75154723da014214f0655" \
-#             && wget -O /tmp/nginx_signing.rsa.pub https://nginx.org/keys/nginx_signing.rsa.pub \
-#             && if echo "$KEY_SHA512 */tmp/nginx_signing.rsa.pub" | sha512sum -c -; then \
-#                 echo "key verification succeeded!"; \
-#                 mv /tmp/nginx_signing.rsa.pub /etc/apk/keys/; \
-#             else \
-#                 echo "key verification failed!"; \
-#                 exit 1; \
-#             fi \
-#             && apk add -X "https://nginx.org/packages/mainline/alpine/v$(egrep -o '^[0-9]+\.[0-9]+' /etc/alpine-release)/main" --no-cache $nginxPackages \
+#     && case "$dpkgArch" in \
+#         amd64|arm64) \
+# # arches officialy built by upstream
+#             echo "deb [signed-by=$NGINX_GPGKEY_PATH] https://nginx.org/packages/mainline/debian/ bookworm nginx" >> /etc/apt/sources.list.d/nginx.list \
+#             && apt-get update \
 #             ;; \
 #         *) \
 # # we're on an architecture upstream doesn't officially build for
-# # let's build binaries from the published packaging sources
-#             set -x \
+# # let's build binaries from the published source packages
+#             echo "deb-src [signed-by=$NGINX_GPGKEY_PATH] https://nginx.org/packages/mainline/debian/ bookworm nginx" >> /etc/apt/sources.list.d/nginx.list \
+#             \
+# # new directory for storing sources and .deb files
 #             && tempDir="$(mktemp -d)" \
-#             && chown nobody:nobody $tempDir \
-#             && apk add --no-cache --virtual .build-deps \
-#                 gcc \
-#                 libc-dev \
-#                 make \
-#                 openssl-dev \
-#                 pcre2-dev \
-#                 zlib-dev \
-#                 linux-headers \
-#                 libxslt-dev \
-#                 gd-dev \
-#                 geoip-dev \
-#                 libedit-dev \
-#                 bash \
-#                 alpine-sdk \
-#                 findutils \
-#             && su nobody -s /bin/sh -c " \
-#                 export HOME=${tempDir} \
-#                 && cd ${tempDir} \
-#                 && curl -f -O https://hg.nginx.org/pkg-oss/archive/${NGINX_VERSION}-${PKG_RELEASE}.tar.gz \
-#                 && PKGOSSCHECKSUM=\"79bf214256bf55700c776a87abfc3cf542323a267d879e89110aa44b551d12f6df7d56676a68f255ebbb54275185980d1fa37075f000d98e0ecac28db9e89fe3 *${NGINX_VERSION}-${PKG_RELEASE}.tar.gz\" \
-#                 && if [ \"\$(openssl sha512 -r ${NGINX_VERSION}-${PKG_RELEASE}.tar.gz)\" = \"\$PKGOSSCHECKSUM\" ]; then \
-#                     echo \"pkg-oss tarball checksum verification succeeded!\"; \
-#                 else \
-#                     echo \"pkg-oss tarball checksum verification failed!\"; \
-#                     exit 1; \
-#                 fi \
-#                 && tar xzvf ${NGINX_VERSION}-${PKG_RELEASE}.tar.gz \
-#                 && cd pkg-oss-${NGINX_VERSION}-${PKG_RELEASE} \
-#                 && cd alpine \
-#                 && make module-geoip module-image-filter module-njs module-xslt \
-#                 && apk index -o ${tempDir}/packages/alpine/${apkArch}/APKINDEX.tar.gz ${tempDir}/packages/alpine/${apkArch}/*.apk \
-#                 && abuild-sign -k ${tempDir}/.abuild/abuild-key.rsa ${tempDir}/packages/alpine/${apkArch}/APKINDEX.tar.gz \
-#                 " \
-#             && cp ${tempDir}/.abuild/abuild-key.rsa.pub /etc/apk/keys/ \
-#             && apk del --no-network .build-deps \
-#             && apk add -X ${tempDir}/packages/alpine/ --no-cache $nginxPackages \
+#             && chmod 777 "$tempDir" \
+# # (777 to ensure APT's "_apt" user can access it too)
+#             \
+# # save list of currently-installed packages so build dependencies can be cleanly removed later
+#             && savedAptMark="$(apt-mark showmanual)" \
+#             \
+# # build .deb files from upstream's source packages (which are verified by apt-get)
+#             && apt-get update \
+#             && apt-get build-dep -y $nginxPackages \
+#             && ( \
+#                 cd "$tempDir" \
+#                 && DEB_BUILD_OPTIONS="nocheck parallel=$(nproc)" \
+#                     apt-get source --compile $nginxPackages \
+#             ) \
+# # we don't remove APT lists here because they get re-downloaded and removed later
+#             \
+# # reset apt-mark's "manual" list so that "purge --auto-remove" will remove all build dependencies
+# # (which is done after we install the built packages so we don't have to redownload any overlapping dependencies)
+#             && apt-mark showmanual | xargs apt-mark auto > /dev/null \
+#             && { [ -z "$savedAptMark" ] || apt-mark manual $savedAptMark; } \
+#             \
+# # create a temporary local APT repo to install from (so that dependency resolution can be handled by APT, as it should be)
+#             && ls -lAFh "$tempDir" \
+#             && ( cd "$tempDir" && dpkg-scanpackages . > Packages ) \
+#             && grep '^Package: ' "$tempDir/Packages" \
+#             && echo "deb [ trusted=yes ] file://$tempDir ./" > /etc/apt/sources.list.d/temp.list \
+# # work around the following APT issue by using "Acquire::GzipIndexes=false" (overriding "/etc/apt/apt.conf.d/docker-gzip-indexes")
+# #   Could not open file /var/lib/apt/lists/partial/_tmp_tmp.ODWljpQfkE_._Packages - open (13: Permission denied)
+# #   ...
+# #   E: Failed to fetch store:/var/lib/apt/lists/partial/_tmp_tmp.ODWljpQfkE_._Packages  Could not open file /var/lib/apt/lists/partial/_tmp_tmp.ODWljpQfkE_._Packages - open (13: Permission denied)
+#             && apt-get -o Acquire::GzipIndexes=false update \
 #             ;; \
 #     esac \
-# # remove checksum deps
-#     && apk del --no-network .checksum-deps \
-# # if we have leftovers from building, let's purge them (including extra, unnecessary build deps)
-#     && if [ -n "$tempDir" ]; then rm -rf "$tempDir"; fi \
-#     && if [ -f "/etc/apk/keys/abuild-key.rsa.pub" ]; then rm -f /etc/apk/keys/abuild-key.rsa.pub; fi \
-#     && if [ -f "/etc/apk/keys/nginx_signing.rsa.pub" ]; then rm -f /etc/apk/keys/nginx_signing.rsa.pub; fi \
-# Bring in curl and ca-certificates to make registering on DNS SD easier
-    && apk add --no-cache curl ca-certificates \
-# Bring in gettext so we can get `envsubst`, then throw
-# the rest away. To do this, we need to install `gettext`
-# then move `envsubst` out of the way so `gettext` can
-# be deleted completely, then move `envsubst` back.
-    && apk add --no-cache --virtual .gettext gettext \
-    && mv /usr/bin/envsubst /tmp/ \
+#     \
+    && apt-get install --no-install-recommends --no-install-suggests -y \
+#                         $nginxPackages \
+                        gettext-base \
+                        curl \
+    && apt-get remove --purge --auto-remove -y && rm -rf /var/lib/apt/lists/* /etc/apt/sources.list.d/nginx.list \
     \
-    && runDeps="$( \
-        scanelf --needed --nobanner /tmp/envsubst \
-            | awk '{ gsub(/,/, "\nso:", $2); print "so:" $2 }' \
-            | sort -u \
-            | xargs -r apk info --installed \
-            | sort -u \
-    )" \
-    && apk add --no-cache $runDeps \
-    && apk del .gettext \
-    && mv /tmp/envsubst /usr/local/bin/ \
-# Bring in tzdata so users could set the timezones through the environment
-# variables
-    && apk add --no-cache tzdata \
+# # if we have leftovers from building, let's purge them (including extra, unnecessary build deps)
+#    && if [ -n "$tempDir" ]; then \
+#        apt-get purge -y --auto-remove \
+#        && rm -rf "$tempDir" /etc/apt/sources.list.d/temp.list; \
+#    fi \
 # forward request and error logs to docker log collector
     && ln -sf /dev/stdout /var/log/nginx/access.log \
     && ln -sf /dev/stderr /var/log/nginx/error.log
+# # create a docker-entrypoint.d directory
+#     && mkdir /docker-entrypoint.d
 
 # Upgrade software to latest version
 # ##############################################################################
-RUN apk upgrade
+RUN apt-get upgrade -y \
+# Cleanup
+# ##############################################################################
+    && apt-get autoremove -y \
+    && rm -rf /var/lib/apt/lists/*
 
 # smoke test
 # ##############################################################################
