sync with official dockerfile + add missing njs (#58)
* sync with official dockerfile + add missing njs
* added conditions to pipelines
* added main dockerfiles
* fixing nested make
* fix patch version from openresty
* fixed dependencies to build njs + docs updated
* fixed the license to have the reference to other dependencies
* fixing missing libxml2 / libxslt dependencies
* fixing broken build steps
* fixing consistency cross dockerfile
* fixing which pkg in almalinux
* added njs support note in readme

diff --git a/tpl/Dockerfile.alpine b/tpl/Dockerfile.alpine
--- a/tpl/Dockerfile.alpine
+++ b/tpl/Dockerfile.alpine
@@ -29,6 +29,7 @@ ARG VCS_REF
 ENV VCS_REF=$VCS_REF
 
 # lua
+# https://www.lua.org/versions.html
 ARG VER_LUA=5.4
 ENV VER_LUA=$VER_LUA
 
@@ -153,6 +154,16 @@ ENV VER_OPENRESTY_STREAMLUA=$VER_OPENRESTY_STREAMLUA
 # https://github.com/nginx/nginx/releases
 ARG VER_NGINX={{VER_NGINX}}
 ENV VER_NGINX=$VER_NGINX
+
+# https://github.com/nginx/njs
+ARG VER_NJS={{VER_NJS}}
+ENV VER_NJS=$VER_NJS
+
+# Replicate same official env variable
+ENV NGINX_VERSION   $VER_NGINX
+ENV NJS_VERSION     $VER_NJS
+ENV PKG_RELEASE     1~$DISTRO_VER
+
 # References:
 #  - https://developers.redhat.com/blog/2018/03/21/compiler-and-linker-flags-gcc
 #  - https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html
@@ -163,6 +174,7 @@ ENV VER_NGINX=$VER_NGINX
 # -Werror=format-security   Reject potentially unsafe format string arguents
 # -Wp,-D_FORTIFY_SOURCE=2   Run-time buffer overflow detection
 # -fPIC                     No text relocations
+# ORIGINAL VALUE: -g -O2 -ffile-prefix-map=/data/builder/debuild/nginx-1.23.3/debian/debuild-base/nginx-1.23.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fPIC
 ARG NGX_CFLAGS="-g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fPIC"
 ENV NGX_CFLAGS=$NGX_CFLAGS
 # References
@@ -175,6 +187,7 @@ ENV NGX_CFLAGS=$NGX_CFLAGS
 # -Wl,-z,now                  Disable lazy binding
 # -Wl,--as-needed             Only link with needed libraries
 # -pie                        Full ASLR for executables
+# ORIGINAL VALUE: -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -pie
 ARG NGX_LDOPT="-Wl,-rpath,/usr/local/lib -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -pie"
 ENV NGX_LDOPT=$NGX_LDOPT
 # Reference: http://nginx.org/en/docs/configure.html
@@ -219,6 +232,7 @@ ARG NGINX_BUILD_CONFIG="\
             --with-stream_realip_module \
             --with-stream_ssl_module \
             --with-stream_ssl_preread_module \
+            --add-module=/njs-${VER_NJS}/nginx \
             --add-module=/lua-nginx-module-${VER_LUA_NGINX_MODULE} \
             --add-module=/ngx_devel_kit-${VER_NGX_DEVEL_KIT} \
             --add-module=/lua-upstream-nginx-module-${VER_LUA_UPSTREAM} \
@@ -259,11 +273,15 @@ ARG NGINX_BUILD_DEPS="\
         alpine-sdk \
         bash \
         findutils \
-        gd-dev \
-        libedit-dev \
+        gcc \
+        libc-dev \
+        libxml2-dev \
         libxslt-dev \
         linux-headers \
-        perl-dev \
+        make \
+        openssl-dev \
+        pcre-dev \
+        zlib-dev \
 "
 ENV NGINX_BUILD_DEPS=$NGINX_BUILD_DEPS
 
@@ -310,6 +328,7 @@ LABEL maintainer="Fabio Cicerchia <info@fabiocicerchia.it>" \
     versions.luarocks="${VER_LUAROCKS}" \
     versions.nginx="${VER_NGINX}" \
     versions.ngx_devel_kit="${VER_NGX_DEVEL_KIT}" \
+    versions.njs="${VER_NJS}" \
     versions.os="{{DOCKER_IMAGE_TAG}}" \
     versions.headers-more-nginx-module="${VER_OPENRESTY_HEADERS}" \
     versions.lua-nginx-module="${VER_LUA_NGINX_MODULE}" \
@@ -331,7 +350,9 @@ LABEL maintainer="Fabio Cicerchia <info@fabiocicerchia.it>" \
     versions.stream-lua-nginx-module="${VER_OPENRESTY_STREAMLUA}"
 
 ARG PKG_DEPS="\
+        curl \
         geoip-dev \
+        libxml2-dev \
         lua${VER_LUA} \
         lua${VER_LUA}-dev \
         openssl-dev \
@@ -363,14 +384,95 @@ RUN set -eux \
     && apk update \
     && apk add --no-cache --virtual .pkg_deps \
         $PKG_DEPS \
+    && mkdir -p /var/log/nginx \
 # Fix LUA alias
-    && ln -sf /usr/bin/lua${VER_LUA} /usr/local/bin/lua \
+    && ln -sf /usr/bin/lua${VER_LUA} /usr/local/bin/lua
+
+RUN set -x \
+# create nginx user/group first, to be consistent throughout docker variants
+    && addgroup -g 101 -S nginx \
+    && adduser -S -D -H -u 101 -h /var/cache/nginx -s /sbin/nologin -G nginx -g nginx nginx \
+# COMMENTED OUT FROM ORIGINAL DOCKERFILE: https://github.com/nginxinc/docker-nginx/blob/1.23.2/mainline/alpine/Dockerfile
+# REASON: No need to use the existing distributed package as the binary is recompiled.
+#     && apkArch="$(cat /etc/apk/arch)" \
+#     && nginxPackages=" \
+#         nginx=${NGINX_VERSION}-r${PKG_RELEASE} \
+#         nginx-module-xslt=${NGINX_VERSION}-r${PKG_RELEASE} \
+#         nginx-module-geoip=${NGINX_VERSION}-r${PKG_RELEASE} \
+#         nginx-module-image-filter=${NGINX_VERSION}-r${PKG_RELEASE} \
+#         nginx-module-njs=${NGINX_VERSION}.${NJS_VERSION}-r${PKG_RELEASE} \
+#     " \
+# # install prerequisites for public key and pkg-oss checks
+#     && apk add --no-cache --virtual .checksum-deps \
+#         openssl \
+#     && case "$apkArch" in \
+#         x86_64|aarch64) \
+# # arches officially built by upstream
+#             set -x \
+#             && KEY_SHA512="e09fa32f0a0eab2b879ccbbc4d0e4fb9751486eedda75e35fac65802cc9faa266425edf83e261137a2f4d16281ce2c1a5f4502930fe75154723da014214f0655" \
+#             && wget -O /tmp/nginx_signing.rsa.pub https://nginx.org/keys/nginx_signing.rsa.pub \
+#             && if echo "$KEY_SHA512 */tmp/nginx_signing.rsa.pub" | sha512sum -c -; then \
+#                 echo "key verification succeeded!"; \
+#                 mv /tmp/nginx_signing.rsa.pub /etc/apk/keys/; \
+#             else \
+#                 echo "key verification failed!"; \
+#                 exit 1; \
+#             fi \
+#             && apk add -X "https://nginx.org/packages/mainline/alpine/v$(egrep -o '^[0-9]+\.[0-9]+' /etc/alpine-release)/main" --no-cache $nginxPackages \
+#             ;; \
+#         *) \
+# # we're on an architecture upstream doesn't officially build for
+# # let's build binaries from the published packaging sources
+#             set -x \
+#             && tempDir="$(mktemp -d)" \
+#             && chown nobody:nobody $tempDir \
+#             && apk add --no-cache --virtual .build-deps \
+#                 gcc \
+#                 libc-dev \
+#                 make \
+#                 openssl-dev \
+#                 pcre2-dev \
+#                 zlib-dev \
+#                 linux-headers \
+#                 bash \
+#                 alpine-sdk \
+#                 findutils \
+#             && su nobody -s /bin/sh -c " \
+#                 export HOME=${tempDir} \
+#                 && cd ${tempDir} \
+#                 && curl -f -O https://hg.nginx.org/pkg-oss/archive/${NGINX_VERSION}-${PKG_RELEASE}.tar.gz \
+#                 && PKGOSSCHECKSUM=\"52a80f6c3b3914462f8a0b2fbadea950bcd79c1bd528386aff4c28d5a80c6920d783575a061a47b60fea800eef66bf5a0178a137ea51c37277fe9c2779715990 *${NGINX_VERSION}-${PKG_RELEASE}.tar.gz\" \
+#                 && if [ \"\$(openssl sha512 -r ${NGINX_VERSION}-${PKG_RELEASE}.tar.gz)\" = \"\$PKGOSSCHECKSUM\" ]; then \
+#                     echo \"pkg-oss tarball checksum verification succeeded!\"; \
+#                 else \
+#                     echo \"pkg-oss tarball checksum verification failed!\"; \
+#                     exit 1; \
+#                 fi \
+#                 && tar xzvf ${NGINX_VERSION}-${PKG_RELEASE}.tar.gz \
+#                 && cd pkg-oss-${NGINX_VERSION}-${PKG_RELEASE} \
+#                 && cd alpine \
+#                 && make base \
+#                 && apk index -o ${tempDir}/packages/alpine/${apkArch}/APKINDEX.tar.gz ${tempDir}/packages/alpine/${apkArch}/*.apk \
+#                 && abuild-sign -k ${tempDir}/.abuild/abuild-key.rsa ${tempDir}/packages/alpine/${apkArch}/APKINDEX.tar.gz \
+#                 " \
+#             && cp ${tempDir}/.abuild/abuild-key.rsa.pub /etc/apk/keys/ \
+#             && apk del .build-deps \
+#             && apk add -X ${tempDir}/packages/alpine/ add--no-cache $nginxPackages \
+#             ;; \
+#     esac \
+# # remove checksum deps
+#     && apk del .checksum-deps \
+# # if we have leftovers from building, let's purge them (including extra, unnecessary build deps)
+#     && if [ -n "$tempDir" ]; then rm -rf "$tempDir"; fi \
+#     && if [ -n "/etc/apk/keys/abuild-key.rsa.pub" ]; then rm -f /etc/apk/keys/abuild-key.rsa.pub; fi \
+#     && if [ -n "/etc/apk/keys/nginx_signing.rsa.pub" ]; then rm -f /etc/apk/keys/nginx_signing.rsa.pub; fi \
 # Bring in gettext so we can get `envsubst`, then throw
 # the rest away. To do this, we need to install `gettext`
 # then move `envsubst` out of the way so `gettext` can
 # be deleted completely, then move `envsubst` back.
     && apk add --no-cache --virtual .gettext gettext \
     && mv /usr/bin/envsubst /tmp/ \
+    \
     && runDeps="$( \
         scanelf --needed --nobanner /tmp/envsubst \
             | awk '{ gsub(/,/, "\nso:", $2); print "so:" $2 }' \
@@ -378,24 +480,19 @@ RUN set -eux \
             | xargs -r apk info --installed \
             | sort -u \
     )" \
-    && apk add --no-cache --virtual .run_deps $runDeps \
+    && apk add --no-cache $runDeps \
     && apk del .gettext \
     && mv /tmp/envsubst /usr/local/bin/ \
 # Bring in tzdata so users could set the timezones through the environment
 # variables
-    && apk add --no-cache --virtual pkg_tz tzdata \
-# Bring in curl and ca-certificates to make registering on DNS SD easier
-    && apk add --no-cache --virtual pkg_dns curl ca-certificates \
+    && apk add --no-cache tzdata \
 # forward request and error logs to docker log collector
-    && mkdir -p /var/log/nginx \
     && ln -sf /dev/stdout /var/log/nginx/access.log \
-    && ln -sf /dev/stderr /var/log/nginx/error.log \
-# create nginx user/group first, to be consistent throughout docker variants
-    && addgroup -g 101 -S nginx \
-    && adduser -S -D -H -u 101 -h /var/cache/nginx -s /sbin/nologin -G nginx -g nginx nginx \
+    && ln -sf /dev/stderr /var/log/nginx/error.log
+
 # Upgrade software to latest version
 # ##############################################################################
-    && apk upgrade
+RUN apk upgrade
 
 # smoke test
 # ##############################################################################
